//! VM artifact building and pipeline management.
//!
//! This module coordinates the building of artifacts required to boot and run
//! virtual machines, such as the kernel, root filesystem, and snapshots.

#![forbid(unsafe_code)]

use crate::error::Result;
#[cfg(feature = "pipeline")]
/// Guest agent building stage.
pub mod guest_agent;
#[cfg(feature = "pipeline")]
/// Guest test-helper (`imp-guest-tools`) building stage.
pub mod guest_tools;
#[cfg(feature = "pipeline")]
/// Kernel building stage.
pub mod kernel;
#[cfg(feature = "pipeline")]
/// Root filesystem building stage.
pub mod rootfs;
#[cfg(feature = "pipeline")]
/// Snapshot building stage.
pub mod snapshot;
/// Tar to EROFS conversion utility.
#[cfg(feature = "am-fs-erofs")]
pub mod tar2erofs;

use std::path::{Path, PathBuf};

/// Inputs for an artifact building stage.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct StageInputs {
    /// Artifacts generated by previous stages.
    pub artifacts: std::collections::HashMap<String, PathBuf>,
    /// Resolved string values (e.g. from pins.json) to pass down.
    pub pins: std::collections::HashMap<String, String>,
}

/// Outputs from an artifact building stage.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct StageOutputs {
    /// Artifacts generated by this stage.
    pub artifacts: std::collections::HashMap<String, PathBuf>,
    /// Resolved string values (e.g. from pins.json) to pass down.
    pub pins: std::collections::HashMap<String, String>,
}

/// A cache key that uniquely identifies the inputs to a stage.
#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CacheKey(pub String);

use async_trait::async_trait;

#[async_trait]
/// A building block of the artifact pipeline.
pub trait Stage: Send + Sync {
    /// The name of this stage.
    fn name(&self) -> &str;
    /// Computes a cache key based on the stage configuration and inputs.
    fn cache_key(&self, inputs: &StageInputs) -> CacheKey;
    /// Returns the target path for the artifact.
    fn out_path(&self, target_dir: &Path) -> PathBuf;
    /// Executes the stage, building the output artifact at the given path.
    ///
    /// # Errors
    /// Returns an error if the build fails.
    async fn run(&self, inputs: &StageInputs, out: &Path) -> Result<StageOutputs>;
}

/// Cache for previously built artifacts.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Cache {}
/// Artifacts resulting from a pipeline build.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Artifacts {
    /// A mapping from artifact name to its location on disk.
    pub paths: std::collections::HashMap<String, PathBuf>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct CacheMetadata {
    key: String,
    hash: String,
    pins: std::collections::HashMap<String, String>,
    #[serde(default)]
    artifacts: std::collections::HashMap<String, PathBuf>,
}

fn hash_file(path: &Path) -> Result<String> {
    use std::io::Read;
    let mut file = std::fs::File::open(path).map_err(crate::error::Error::Io)?;
    let mut hasher = blake3::Hasher::new();
    let mut buf = [0; 65536];
    loop {
        let n = file.read(&mut buf).map_err(crate::error::Error::Io)?;
        if n == 0 {
            break;
        }
        hasher.update(buf.get(..n).expect("valid slice"));
    }
    Ok(hasher.finalize().to_hex().to_string())
}

/// Folds the upstream `artifacts` into `hasher` in a deterministic, key-sorted order,
/// hashing each artifact's on-disk **content** (the identity that travels) rather than its
/// absolute path under `target_dir`. Falls back to the path identity only if the artifact
/// is not yet materialized on disk.
///
/// Iterating the raw `HashMap` would feed blake3 in a process-random order (spurious cache
/// misses) and would key on `target_dir`-relative path strings (a rebuilt upstream at the
/// same path would not invalidate the key). Sorting + content-hashing fixes both.
#[cfg(feature = "pipeline")]
pub(crate) fn hash_artifacts_sorted(
    hasher: &mut blake3::Hasher,
    artifacts: &std::collections::HashMap<String, PathBuf>,
) {
    let sorted: std::collections::BTreeMap<&String, &PathBuf> = artifacts.iter().collect();
    for (k, v) in sorted {
        hasher.update(k.as_bytes());
        match hash_file(v) {
            Ok(content_hash) => {
                hasher.update(b"c:");
                hasher.update(content_hash.as_bytes());
            }
            Err(_) => {
                hasher.update(b"p:");
                hasher.update(v.to_string_lossy().as_bytes());
            }
        }
    }
}

/// Parses the resolved-pins JSON document into a flat map of pin keys.
///
/// Extracted as a pure helper so the pin extraction (including the
/// `debian_snapshot_timestamp` the mmdebstrap source depends on) is unit-testable.
fn parse_pins_json(content: &str) -> std::collections::HashMap<String, String> {
    let mut pins_map = std::collections::HashMap::new();
    if let Ok(json) = serde_json::from_str::<serde_json::Value>(content) {
        if let Some(k) = json.get("kernel") {
            if let Some(sha) = k.get("source_sha256").and_then(|v| v.as_str()) {
                pins_map.insert("kernel_source_sha256".to_string(), sha.to_string());
            }
            if let Some(url) = k.get("source_url").and_then(|v| v.as_str()) {
                pins_map.insert("kernel_source_url".to_string(), url.to_string());
            }
            if let Some(cfg) = k.get("microvm_config").and_then(|v| v.as_str()) {
                pins_map.insert("kernel_microvm_config".to_string(), cfg.to_string());
            }
        }
        if let Some(r) = json.get("rootfs") {
            if let Some(img) = r.get("image").and_then(|v| v.as_str()) {
                pins_map.insert("rootfs_image".to_string(), img.to_string());
            }
            if let Some(dig) = r.get("digest").and_then(|v| v.as_str()) {
                pins_map.insert("rootfs_digest".to_string(), dig.to_string());
            }
        }
        // Emit the Debian snapshot.debian.org timestamp pin if present (top-level or under
        // `rootfs`) so the mmdebstrap source has its required source timestamp.
        let ts = json
            .get("debian_snapshot_timestamp")
            .and_then(|v| v.as_str())
            .or_else(|| {
                json.get("rootfs")
                    .and_then(|r| r.get("debian_snapshot_timestamp"))
                    .and_then(|v| v.as_str())
            });
        if let Some(ts) = ts {
            pins_map.insert("debian_snapshot_timestamp".to_string(), ts.to_string());
        }
    }
    pins_map
}

/// Computes the blake3 hash of the guest-agent source file at `path`.
///
/// # Errors
/// Returns [`crate::error::Error::Artifact`] if the source cannot be read. This is a hard
/// stop on purpose: a missing guest-agent source must not silently degrade to an `"unknown"`
/// pin (which would leave a stale agent baked into every downstream rootfs).
fn guest_agent_src_hash(path: &Path) -> Result<String> {
    let src = std::fs::read_to_string(path).map_err(|e| {
        crate::error::Error::Artifact(format!(
            "failed to read guest-agent source at {}: {}",
            path.display(),
            e
        ))
    })?;
    let mut hasher = blake3::Hasher::new();
    hasher.update(src.as_bytes());
    Ok(hasher.finalize().to_hex().to_string())
}

/// Resolves the absolute path to the guest-agent source, anchored at the crate root
/// (`CARGO_MANIFEST_DIR`) rather than the process CWD.
fn guest_agent_src_path() -> PathBuf {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".to_string());
    Path::new(&manifest_dir).join("src/bin/imp-guest-agent.rs")
}

/// A pipeline of stages to build all necessary test VM artifacts.
pub struct Pipeline {
    /// The sequence of stages to run.
    pub stages: Vec<Box<dyn Stage>>,
    /// The target directory for built artifacts.
    pub target_dir: PathBuf,
}

impl std::fmt::Debug for Pipeline {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Pipeline {{ {} stages }}", self.stages.len())
    }
}

impl Pipeline {
    /// Builds all artifacts in the pipeline.
    ///
    /// # Errors
    /// Returns an error if any stage fails.
    pub async fn build(&self, _cache: &Cache) -> Result<Artifacts> {
        let dir = &self.target_dir;
        match tokio::fs::create_dir_all(dir).await {
            Ok(_) => {}
            Err(e) => return Err(crate::error::Error::Io(e)),
        }

        let mut inputs = StageInputs::default();

        for stage in &self.stages {
            let out_path = stage.out_path(dir);

            let key = stage.cache_key(&inputs);
            let key_path = out_path.with_extension("cache_key");

            let mut cached = false;
            let mut cached_pins = std::collections::HashMap::new();
            let mut cached_artifacts = std::collections::HashMap::new();

            if out_path.exists() && key_path.exists() {
                if let Ok(metadata_str) = std::fs::read_to_string(&key_path) {
                    if let Ok(metadata) = serde_json::from_str::<CacheMetadata>(&metadata_str) {
                        if metadata.key == key.0 {
                            if let Ok(actual_hash) = hash_file(&out_path) {
                                if actual_hash == metadata.hash {
                                    cached = true;
                                    cached_pins = metadata.pins;
                                    cached_artifacts = metadata.artifacts;
                                } else {
                                    return Err(crate::error::Error::Artifact(format!(
                                        "Tampered artifact for stage {}: payload hash mismatch",
                                        stage.name()
                                    )));
                                }
                            }
                        }
                    } else {
                        // Fallback for old cache key format: just a string
                        if metadata_str == key.0 {
                            // Can't verify hash or recover pins. Miss cache to force rebuild and get proper format.
                            tracing::warn!(
                                "Cache invalid for stage {}: old cache format",
                                stage.name()
                            );
                        }
                    }
                }
            }

            if cached {
                tracing::info!("Skipping stage {} (cached)", stage.name());
                if cached_artifacts.is_empty() {
                    inputs
                        .artifacts
                        .insert(stage.name().to_string(), out_path.clone());
                } else {
                    for (k, v) in cached_artifacts {
                        inputs.artifacts.insert(k, v);
                    }
                }
                for (k, v) in cached_pins {
                    inputs.pins.insert(k, v);
                }
            } else {
                tracing::info!("Running stage {}", stage.name());
                let outputs = stage.run(&inputs, &out_path).await?;

                // Hash payload and write metadata
                if out_path.exists() {
                    match hash_file(&out_path) {
                        Ok(hash) => {
                            let metadata = CacheMetadata {
                                key: key.0.clone(),
                                hash,
                                pins: outputs.pins.clone(),
                                artifacts: outputs.artifacts.clone(),
                            };
                            if let Ok(json) = serde_json::to_string(&metadata) {
                                if let Err(e) = std::fs::write(&key_path, json) {
                                    tracing::warn!(
                                        "Failed to write cache key for stage {}: {}",
                                        stage.name(),
                                        e
                                    );
                                }
                            }
                        }
                        Err(e) => {
                            tracing::warn!(
                                "Failed to hash output for stage {}: {}",
                                stage.name(),
                                e
                            );
                        }
                    }
                }

                for (k, v) in outputs.artifacts {
                    inputs.artifacts.insert(k, v);
                }
                for (k, v) in outputs.pins {
                    inputs.pins.insert(k, v);
                }
            }
        }

        Ok(Artifacts {
            paths: inputs.artifacts,
        })
    }

    /// Resets the pipeline to run a specific stage again.
    ///
    /// # Errors
    /// Returns an error if the reset fails.
    pub fn reset_to(&self, stage: &str, _cache: &Cache) -> Result<()> {
        let dir = &self.target_dir;
        let mut found = false;
        for s in &self.stages {
            if s.name() == stage {
                found = true;
            }
            if found {
                let out_path = s.out_path(dir);
                let key_path = out_path.with_extension("cache_key");
                if out_path.exists() {
                    let _ = std::fs::remove_file(&out_path);
                }
                if key_path.exists() {
                    let _ = std::fs::remove_file(&key_path);
                }
            }
        }
        if !found {
            return Err(crate::error::Error::Artifact(format!(
                "Stage not found: {}",
                stage
            )));
        }
        Ok(())
    }
}

/// A pipeline stage that resolves abstract versions into exact cryptographic hashes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvePinsStage {
    /// Path to the pins.json file.
    pub pins_file: PathBuf,
}

#[async_trait]
impl Stage for ResolvePinsStage {
    fn name(&self) -> &str {
        "resolve_pins"
    }

    fn cache_key(&self, _inputs: &StageInputs) -> CacheKey {
        // Bump when this stage's resolution logic changes so stale outputs are not served.
        const STAGE_VERSION: u32 = 1;
        let content = std::fs::read_to_string(&self.pins_file).unwrap_or_default();
        let mut hasher = blake3::Hasher::new();
        hasher.update(&STAGE_VERSION.to_le_bytes());
        hasher.update(content.as_bytes());
        // Fold the guest-agent source identity into the key so an agent-source change
        // invalidates the resolved pins (otherwise a cache hit here would skip re-hashing
        // the agent and a stale `guest_agent_src_hash` would propagate downstream).
        let agent_src = std::fs::read_to_string(guest_agent_src_path()).unwrap_or_default();
        hasher.update(agent_src.as_bytes());
        CacheKey(format!("resolve-pins-{}", hasher.finalize().to_hex()))
    }

    fn out_path(&self, target_dir: &Path) -> PathBuf {
        target_dir.join("resolved_pins.json")
    }

    async fn run(&self, _inputs: &StageInputs, out: &Path) -> Result<StageOutputs> {
        let content = tokio::fs::read_to_string(&self.pins_file)
            .await
            .map_err(crate::error::Error::Io)?;
        tokio::fs::write(out, &content)
            .await
            .map_err(crate::error::Error::Io)?;

        let mut pins_map = parse_pins_json(&content);

        // Resolve the guest-agent source hash from an absolute, crate-anchored path and FAIL
        // HARD if it is missing. A silent `"unknown"` fallback (CWD-relative) would bake a
        // stale agent into every downstream rootfs without invalidating any cache key.
        let agent_src = guest_agent_src_path();
        let agent_hash = guest_agent_src_hash(&agent_src)?;
        pins_map.insert("guest_agent_src_hash".to_string(), agent_hash);

        let mut outputs = StageOutputs::default();
        outputs
            .artifacts
            .insert("resolved_pins".to_string(), out.to_path_buf());
        outputs.pins = pins_map;
        Ok(outputs)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Guards ARTIFACT-PIPELINE-5: a buggy impl that never emits
    // `debian_snapshot_timestamp` (so the mmdebstrap source can't run) goes red here.
    #[test]
    fn test_parse_pins_emits_debian_snapshot_timestamp() {
        let top = r#"{ "debian_snapshot_timestamp": "20240101T000000Z" }"#;
        let map = parse_pins_json(top);
        assert_eq!(
            map.get("debian_snapshot_timestamp").map(String::as_str),
            Some("20240101T000000Z")
        );

        // Also accepted when nested under `rootfs`.
        let nested = r#"{ "rootfs": { "image": "docker.io/library/debian",
            "digest": "sha256:abc", "debian_snapshot_timestamp": "20240202T000000Z" } }"#;
        let map = parse_pins_json(nested);
        assert_eq!(
            map.get("debian_snapshot_timestamp").map(String::as_str),
            Some("20240202T000000Z")
        );
        assert_eq!(
            map.get("rootfs_digest").map(String::as_str),
            Some("sha256:abc")
        );
    }

    // Guards DESIGN-DIVERGENCE-3: a buggy impl that swallows a missing guest-agent source
    // into an `"unknown"` pin (instead of failing hard) would return Ok here.
    #[test]
    fn test_guest_agent_src_hash_fails_hard_on_missing() {
        let missing = Path::new("/nonexistent/imp/does-not-exist/imp-guest-agent.rs");
        let res = guest_agent_src_hash(missing);
        assert!(
            matches!(res, Err(crate::error::Error::Artifact(_))),
            "missing guest-agent source must be a hard error, got {res:?}"
        );
    }

    // Guards DESIGN-DIVERGENCE-3 (the hash actually tracks content): different source
    // bytes must yield a different hash, and the same bytes a stable one.
    #[test]
    fn test_guest_agent_src_hash_tracks_content() {
        let dir = tempfile::tempdir().expect("tempdir");
        let p = dir.path().join("agent.rs");
        std::fs::write(&p, b"fn main() {}").expect("write");
        let h1 = guest_agent_src_hash(&p).expect("hash");
        let h1b = guest_agent_src_hash(&p).expect("hash");
        assert_eq!(h1, h1b, "hash must be deterministic for identical content");

        std::fs::write(&p, b"fn main() { /* changed */ }").expect("write");
        let h2 = guest_agent_src_hash(&p).expect("hash");
        assert_ne!(h1, h2, "changed source content must change the hash");
    }
}
