//! VM artifact building and pipeline management.
//!
//! This module coordinates the building of artifacts required to boot and run
//! virtual machines, such as the kernel, root filesystem, and snapshots.

#![forbid(unsafe_code)]

use crate::error::Result;
#[cfg(feature = "pipeline")]
/// Guest agent building stage.
pub mod guest_agent;
#[cfg(feature = "pipeline")]
/// Guest test-helper (`vmcell-guest-tools`) building stage.
pub mod guest_tools;
#[cfg(feature = "pipeline")]
/// Kernel building stage.
pub mod kernel;
#[cfg(feature = "pipeline")]
/// Root filesystem building stage.
pub mod rootfs;
#[cfg(feature = "pipeline")]
/// Snapshot building stage.
pub mod snapshot;
/// Tar to EROFS conversion utility.
#[cfg(feature = "am-fs-erofs")]
pub mod tar2erofs;

use std::path::{Path, PathBuf};

/// The VM-artifacts directory: `$VMCELL_ARTIFACTS_DIR` or the default `target/vmcell-artifacts`.
/// The single source of truth for where built artifacts (kernel, rootfs, CA) live.
#[must_use]
pub fn artifacts_dir() -> PathBuf {
    resolve_artifacts_dir(std::env::var_os("VMCELL_ARTIFACTS_DIR"))
}

/// Pure resolver behind [`artifacts_dir`], factored out so the default can be unit-tested
/// without mutating (and racing on) the process environment.
fn resolve_artifacts_dir(var: Option<std::ffi::OsString>) -> PathBuf {
    var.map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("target/vmcell-artifacts"))
}

/// The guest kernel image path: `$VMCELL_KERNEL`, else `<artifacts_dir>/vmlinux`.
#[must_use]
pub fn kernel_path() -> PathBuf {
    std::env::var_os("VMCELL_KERNEL")
        .map(PathBuf::from)
        .unwrap_or_else(|| artifacts_dir().join("vmlinux"))
}

/// The rootfs erofs path: `$VMCELL_ROOTFS`, else `<artifacts_dir>/rootfs.erofs`.
#[must_use]
pub fn rootfs_path() -> PathBuf {
    std::env::var_os("VMCELL_ROOTFS")
        .map(PathBuf::from)
        .unwrap_or_else(|| artifacts_dir().join("rootfs.erofs"))
}

/// The cloud-hypervisor binary path: `$VMCELL_CH_BIN`, else bare `cloud-hypervisor`
/// (resolved on `PATH`).
///
/// The single source of truth for the CH binary so every stage that boots a VM
/// (the snapshot stage and the mmdebstrap builder stage) reads the **same** env var.
/// Previously the snapshot stage read `CLOUD_HYPERVISOR_PATH` while the builder read
/// `VMCELL_CH_BIN`, so overriding one left the other on the default — the kind of
/// per-call-site drift §11.1 consolidation and the `VMCELL_*` namespacing of §10.7-C
/// exist to prevent.
#[cfg(feature = "pipeline")]
pub(crate) fn ch_binary_path() -> String {
    std::env::var("VMCELL_CH_BIN").unwrap_or_else(|_| "cloud-hypervisor".to_string())
}

/// Inputs for an artifact building stage.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
#[non_exhaustive]
pub struct StageInputs {
    /// Artifacts generated by previous stages.
    pub artifacts: std::collections::HashMap<String, PathBuf>,
    /// Resolved string values (e.g. from pins.json) to pass down.
    pub pins: std::collections::HashMap<String, String>,
}

/// Outputs from an artifact building stage.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
#[non_exhaustive]
pub struct StageOutputs {
    /// Artifacts generated by this stage.
    pub artifacts: std::collections::HashMap<String, PathBuf>,
    /// Resolved string values (e.g. from pins.json) to pass down.
    pub pins: std::collections::HashMap<String, String>,
}

/// A cache key that uniquely identifies the inputs to a stage.
#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub struct CacheKey(pub String);

impl CacheKey {
    /// Wraps a precomputed cache-key string.
    ///
    /// Out-of-crate [`Stage`] implementations must use this constructor: the type
    /// is `#[non_exhaustive]`, so the tuple cannot be built directly from another
    /// crate.
    #[must_use]
    pub fn new(key: String) -> Self {
        Self(key)
    }
}

use async_trait::async_trait;

#[async_trait]
/// A building block of the artifact pipeline.
pub trait Stage: Send + Sync {
    /// The name of this stage.
    fn name(&self) -> &str;
    /// Computes a cache key based on the stage configuration and inputs.
    fn cache_key(&self, inputs: &StageInputs) -> CacheKey;
    /// Returns the target path for the artifact.
    fn out_path(&self, target_dir: &Path) -> PathBuf;
    /// Executes the stage, building the output artifact at the given path.
    ///
    /// # Errors
    /// Returns an error if the build fails.
    async fn run(&self, inputs: &StageInputs, out: &Path) -> Result<StageOutputs>;
}

/// Cache for previously built artifacts.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Cache {}
/// Artifacts resulting from a pipeline build.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub struct Artifacts {
    /// A mapping from artifact name to its location on disk.
    pub paths: std::collections::HashMap<String, PathBuf>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct CacheMetadata {
    key: String,
    hash: String,
    pins: std::collections::HashMap<String, String>,
    #[serde(default)]
    artifacts: std::collections::HashMap<String, PathBuf>,
}

fn hash_file(path: &Path) -> Result<String> {
    use std::io::Read;
    let mut file = std::fs::File::open(path).map_err(crate::error::Error::Io)?;
    let mut hasher = blake3::Hasher::new();
    let mut buf = [0; 65536];
    loop {
        let n = file.read(&mut buf).map_err(crate::error::Error::Io)?;
        if n == 0 {
            break;
        }
        hasher.update(buf.get(..n).expect("valid slice"));
    }
    Ok(hasher.finalize().to_hex().to_string())
}

/// Removes `path` if it exists, returning `Ok(())` when it is already absent and
/// propagating every other I/O error (e.g. permission denied, path-is-a-directory).
///
/// Used by [`Pipeline::reset_to`] so a failed invalidation is loud, never a
/// silent `Ok` that leaves a stale cached artifact behind.
///
/// # Errors
/// Returns [`crate::error::Error::Io`] if the file exists but cannot be removed.
fn remove_if_present(path: &Path) -> Result<()> {
    match std::fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(crate::error::Error::Io(e)),
    }
}

/// Folds the upstream `artifacts` into `hasher` in a deterministic, key-sorted order,
/// hashing each artifact's on-disk **content** (the identity that travels) rather than its
/// absolute path under `target_dir`. Falls back to the path identity only if the artifact
/// is not yet materialized on disk.
///
/// Iterating the raw `HashMap` would feed blake3 in a process-random order (spurious cache
/// misses) and would key on `target_dir`-relative path strings (a rebuilt upstream at the
/// same path would not invalidate the key). Sorting + content-hashing fixes both.
#[cfg(feature = "pipeline")]
pub(crate) fn hash_artifacts_sorted(
    hasher: &mut blake3::Hasher,
    artifacts: &std::collections::HashMap<String, PathBuf>,
) {
    let sorted: std::collections::BTreeMap<&String, &PathBuf> = artifacts.iter().collect();
    for (k, v) in sorted {
        hasher.update(k.as_bytes());
        match hash_file(v) {
            Ok(content_hash) => {
                hasher.update(b"c:");
                hasher.update(content_hash.as_bytes());
            }
            Err(_) => {
                hasher.update(b"p:");
                hasher.update(v.to_string_lossy().as_bytes());
            }
        }
    }
}

/// Parses the resolved-pins JSON document into a flat map of pin keys.
///
/// Extracted as a pure helper so the pin extraction (including the
/// `debian_snapshot_timestamp` the mmdebstrap source depends on) is unit-testable.
///
/// # Errors
/// Returns [`crate::error::Error::Artifact`] if `content` is not valid JSON. A
/// tampered/garbled `pins.json` must fail loud here — the old code swallowed the
/// parse error and degraded to an empty map, which only surfaced later as a
/// misleading "Missing X pin" far from the real cause (A8 — verify what you ingest).
fn parse_pins_json(content: &str) -> Result<std::collections::HashMap<String, String>> {
    let json = serde_json::from_str::<serde_json::Value>(content)
        .map_err(|e| crate::error::Error::Artifact(format!("malformed pins JSON: {e}")))?;
    let mut pins_map = std::collections::HashMap::new();
    if let Some(k) = json.get("kernel") {
        if let Some(sha) = k.get("source_sha256").and_then(|v| v.as_str()) {
            pins_map.insert("kernel_source_sha256".to_string(), sha.to_string());
        }
        if let Some(url) = k.get("source_url").and_then(|v| v.as_str()) {
            pins_map.insert("kernel_source_url".to_string(), url.to_string());
        }
        if let Some(cfg) = k.get("microvm_config").and_then(|v| v.as_str()) {
            pins_map.insert("kernel_microvm_config".to_string(), cfg.to_string());
        }
    }
    // Flatten the multi-kernel registry: each `kernels.<label>` → keyed pins
    // (`kernel_<label>_source_url` / `_source_sha256`), so a labelled `KernelStage`
    // can build `vmlinux-<label>` — the kernel-version benchmark dimension. They
    // share the default `kernel`'s `microvm_config`.
    if let Some(kernels) = json.get("kernels").and_then(|v| v.as_object()) {
        for (label, spec) in kernels {
            if let Some(url) = spec.get("source_url").and_then(|v| v.as_str()) {
                pins_map.insert(format!("kernel_{label}_source_url"), url.to_string());
            }
            if let Some(sha) = spec.get("source_sha256").and_then(|v| v.as_str()) {
                pins_map.insert(format!("kernel_{label}_source_sha256"), sha.to_string());
            }
        }
    }
    if let Some(r) = json.get("rootfs") {
        if let Some(img) = r.get("image").and_then(|v| v.as_str()) {
            pins_map.insert("rootfs_image".to_string(), img.to_string());
        }
        if let Some(dig) = r.get("digest").and_then(|v| v.as_str()) {
            pins_map.insert("rootfs_digest".to_string(), dig.to_string());
        }
    }
    // Emit the Debian snapshot.debian.org timestamp pin if present (top-level or under
    // `rootfs`) so the mmdebstrap source has its required source timestamp.
    let ts = json
        .get("debian_snapshot_timestamp")
        .and_then(|v| v.as_str())
        .or_else(|| {
            json.get("rootfs")
                .and_then(|r| r.get("debian_snapshot_timestamp"))
                .and_then(|v| v.as_str())
        });
    if let Some(ts) = ts {
        pins_map.insert("debian_snapshot_timestamp".to_string(), ts.to_string());
    }
    Ok(pins_map)
}

/// Computes the blake3 hash of the guest-agent source file at `path`.
///
/// # Errors
/// Returns [`crate::error::Error::Artifact`] if the source cannot be read. This is a hard
/// stop on purpose: a missing guest-agent source must not silently degrade to an `"unknown"`
/// pin (which would leave a stale agent baked into every downstream rootfs).
fn guest_agent_src_hash(path: &Path) -> Result<String> {
    let src = std::fs::read_to_string(path).map_err(|e| {
        crate::error::Error::Artifact(format!(
            "failed to read guest-agent source at {}: {}",
            path.display(),
            e
        ))
    })?;
    let mut hasher = blake3::Hasher::new();
    hasher.update(src.as_bytes());
    Ok(hasher.finalize().to_hex().to_string())
}

/// The crate root (`CARGO_MANIFEST_DIR`, else the CWD), the anchor for the
/// guest-agent source closure. Anchored at the crate rather than the process CWD
/// so the closure hash is stable regardless of where the pipeline is invoked.
fn guest_agent_crate_root() -> PathBuf {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".to_string());
    PathBuf::from(manifest_dir)
}

/// Recursively collects every `*.rs` file under `dir` into `out`.
///
/// # Errors
/// Returns [`crate::error::Error::Artifact`] if `dir` (or a subdirectory) cannot
/// be read — the agent logic must exist, so a missing source tree is a hard stop
/// rather than a silent partial hash.
fn collect_rs_files(dir: &Path, out: &mut Vec<PathBuf>) -> Result<()> {
    let entries = std::fs::read_dir(dir).map_err(|e| {
        crate::error::Error::Artifact(format!(
            "failed to read guest-agent source dir {}: {}",
            dir.display(),
            e
        ))
    })?;
    for entry in entries {
        let entry = entry.map_err(crate::error::Error::Io)?;
        let file_type = entry.file_type().map_err(crate::error::Error::Io)?;
        let path = entry.path();
        if file_type.is_dir() {
            collect_rs_files(&path, out)?;
        } else if path.extension().and_then(|e| e.to_str()) == Some("rs") {
            out.push(path);
        }
    }
    Ok(())
}

/// Hashes the **full source closure** the `vmcell-guest-agent` binary compiles from:
/// the thin binary wrapper (`src/bin/vmcell-guest-agent.rs`) **plus** every `*.rs`
/// under `src/agent/` (the real logic it links — `ReaperCoordinator`,
/// `exit_code_from_termination`, the wire `protocol`) **plus** `Cargo.lock` (the
/// pinned dependency versions). All paths are taken relative to `crate_root` and
/// folded in a deterministic, sorted order.
///
/// Hashing only the wrapper (the old behavior) left every downstream cache key
/// blind to a change in `src/agent/**`: editing the reaper or the post-restore
/// vsock re-bind left the hash unchanged, so all three cache keys (resolve-pins,
/// guest-agent, rootfs) hit and a **stale agent binary was re-baked into
/// `rootfs.erofs`**. The closure must travel as one identity (H-CACHE-1).
///
/// # Errors
/// Returns [`crate::error::Error::Artifact`] if the binary wrapper is missing, the
/// `src/agent` tree cannot be read, or any closure file cannot be read — a hard
/// stop, never a silent partial or `"unknown"` hash.
fn guest_agent_closure_hash(crate_root: &Path) -> Result<String> {
    // The bin wrapper is mandatory; its absence is the same hard stop as before.
    let bin = crate_root.join("src/bin/vmcell-guest-agent.rs");
    if !bin.is_file() {
        return Err(crate::error::Error::Artifact(format!(
            "guest-agent binary source missing at {}",
            bin.display()
        )));
    }
    let mut files: Vec<PathBuf> = vec![bin];
    // Every Rust source file under src/agent/ that the binary links.
    collect_rs_files(&crate_root.join("src/agent"), &mut files)?;
    // Cargo.lock pins the dependency versions the agent compiles against; fold it
    // if present (a workspace may build the lock only on demand).
    let lock = crate_root.join("Cargo.lock");
    if lock.is_file() {
        files.push(lock);
    }
    // Deterministic order regardless of `read_dir` order.
    files.sort();

    let mut hasher = blake3::Hasher::new();
    for f in &files {
        // Fold the crate-relative path (so a rename/move invalidates) with an
        // unambiguous delimiter, then the file's content hash.
        let rel = f.strip_prefix(crate_root).unwrap_or(f.as_path());
        hasher.update(rel.to_string_lossy().as_bytes());
        hasher.update(b"\0");
        hasher.update(guest_agent_src_hash(f)?.as_bytes());
        hasher.update(b"\0");
    }
    Ok(hasher.finalize().to_hex().to_string())
}

/// Hashes the **source closure** the `vmcell-guest-tools` helper binary compiles
/// from: its thin binary source (`src/bin/vmcell-guest-tools.rs`) **plus**
/// `Cargo.lock` (the pinned dependency versions). Files are taken relative to
/// `crate_root` and folded in a deterministic, sorted order with a stable hasher
/// (blake3) — mirroring [`guest_agent_closure_hash`].
///
/// Folding `Cargo.lock` is the whole point: `vmcell-guest-tools` links
/// reqwest/rustls, so a dependency bump changes the **built** helper while the
/// `.rs` source is byte-identical. Hashing only the source (the old behavior) left
/// the cache key unchanged on a bump, so the stage hit cache and a stale
/// `ip`/`curl`/`kvm-ok` helper was re-baked into the rootfs (§11.2 caching rules
/// 3-4). The closure must travel as one identity.
///
/// # Errors
/// Returns [`crate::error::Error::Artifact`] if the binary source is missing, or
/// any closure file cannot be read — a hard stop, never a silent partial hash (the
/// old `if let Ok(content)` swallow that quietly produced a content-blind key).
#[cfg(feature = "pipeline")]
pub(crate) fn guest_tools_closure_hash(crate_root: &Path) -> Result<String> {
    // The bin source is mandatory; its absence is a hard stop.
    let bin = crate_root.join("src/bin/vmcell-guest-tools.rs");
    if !bin.is_file() {
        return Err(crate::error::Error::Artifact(format!(
            "guest-tools binary source missing at {}",
            bin.display()
        )));
    }
    let mut files: Vec<PathBuf> = vec![bin];
    // Cargo.lock pins the dependency versions the helper compiles against; fold it
    // if present (a workspace may build the lock only on demand).
    let lock = crate_root.join("Cargo.lock");
    if lock.is_file() {
        files.push(lock);
    }
    // Deterministic order regardless of filesystem enumeration.
    files.sort();

    let mut hasher = blake3::Hasher::new();
    for f in &files {
        // Fold the crate-relative path (so a rename/move invalidates) with an
        // unambiguous delimiter, then the file's content hash. `guest_agent_src_hash`
        // is a generic fail-hard file-content hash reused here.
        let rel = f.strip_prefix(crate_root).unwrap_or(f.as_path());
        hasher.update(rel.to_string_lossy().as_bytes());
        hasher.update(b"\0");
        hasher.update(guest_agent_src_hash(f)?.as_bytes());
        hasher.update(b"\0");
    }
    Ok(hasher.finalize().to_hex().to_string())
}

/// A pipeline of stages to build all necessary test VM artifacts.
///
/// The fields are private: a stage list is only assembled through
/// [`Pipeline::new`] + [`Pipeline::add_stage`], so an external caller cannot
/// mutate `stages` to drop or reorder Stage 0 (`ResolvePinsStage`) and bypass the
/// "Stage 0 resolves pins" invariant.
pub struct Pipeline {
    /// The sequence of stages to run.
    stages: Vec<Box<dyn Stage>>,
    /// The target directory for built artifacts.
    target_dir: PathBuf,
}

impl std::fmt::Debug for Pipeline {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Pipeline {{ {} stages }}", self.stages.len())
    }
}

impl Pipeline {
    /// Creates an empty pipeline that writes artifacts under `target_dir`.
    #[must_use]
    pub fn new(target_dir: PathBuf) -> Self {
        Self {
            stages: Vec::new(),
            target_dir,
        }
    }

    /// Appends a stage to the pipeline, returning `self` for chaining.
    #[must_use]
    pub fn add_stage(mut self, stage: Box<dyn Stage>) -> Self {
        self.stages.push(stage);
        self
    }

    /// Builds all artifacts in the pipeline.
    ///
    /// # Errors
    /// Returns an error if any stage fails.
    pub async fn build(&self, _cache: &Cache) -> Result<Artifacts> {
        let dir = &self.target_dir;
        match tokio::fs::create_dir_all(dir).await {
            Ok(_) => {}
            Err(e) => return Err(crate::error::Error::Io(e)),
        }

        let mut inputs = StageInputs::default();

        for stage in &self.stages {
            let out_path = stage.out_path(dir);

            let key = stage.cache_key(&inputs);
            let key_path = out_path.with_extension("cache_key");

            let mut cached = false;
            let mut cached_pins = std::collections::HashMap::new();
            let mut cached_artifacts = std::collections::HashMap::new();

            if out_path.exists() && key_path.exists() {
                if let Ok(metadata_str) = std::fs::read_to_string(&key_path) {
                    if let Ok(metadata) = serde_json::from_str::<CacheMetadata>(&metadata_str) {
                        if metadata.key == key.0 {
                            if let Ok(actual_hash) = hash_file(&out_path) {
                                if actual_hash == metadata.hash {
                                    cached = true;
                                    cached_pins = metadata.pins;
                                    cached_artifacts = metadata.artifacts;
                                } else {
                                    return Err(crate::error::Error::Artifact(format!(
                                        "Tampered artifact for stage {}: payload hash mismatch",
                                        stage.name()
                                    )));
                                }
                            }
                        }
                    } else {
                        // Fallback for old cache key format: just a string
                        if metadata_str == key.0 {
                            // Can't verify hash or recover pins. Miss cache to force rebuild and get proper format.
                            tracing::warn!(
                                "Cache invalid for stage {}: old cache format",
                                stage.name()
                            );
                        }
                    }
                }
            }

            if cached {
                tracing::info!("Skipping stage {} (cached)", stage.name());
                if cached_artifacts.is_empty() {
                    inputs
                        .artifacts
                        .insert(stage.name().to_string(), out_path.clone());
                } else {
                    for (k, v) in cached_artifacts {
                        inputs.artifacts.insert(k, v);
                    }
                }
                for (k, v) in cached_pins {
                    inputs.pins.insert(k, v);
                }
            } else {
                tracing::info!("Running stage {}", stage.name());
                let outputs = stage.run(&inputs, &out_path).await?;

                // Hash payload and write metadata
                if out_path.exists() {
                    match hash_file(&out_path) {
                        Ok(hash) => {
                            let metadata = CacheMetadata {
                                key: key.0.clone(),
                                hash,
                                pins: outputs.pins.clone(),
                                artifacts: outputs.artifacts.clone(),
                            };
                            if let Ok(json) = serde_json::to_string(&metadata) {
                                if let Err(e) = std::fs::write(&key_path, json) {
                                    tracing::warn!(
                                        "Failed to write cache key for stage {}: {}",
                                        stage.name(),
                                        e
                                    );
                                }
                            }
                        }
                        Err(e) => {
                            tracing::warn!(
                                "Failed to hash output for stage {}: {}",
                                stage.name(),
                                e
                            );
                        }
                    }
                }

                for (k, v) in outputs.artifacts {
                    inputs.artifacts.insert(k, v);
                }
                for (k, v) in outputs.pins {
                    inputs.pins.insert(k, v);
                }
            }
        }

        Ok(Artifacts {
            paths: inputs.artifacts,
        })
    }

    /// Resets the pipeline to run a specific stage again.
    ///
    /// # Errors
    /// Returns an error if the reset fails.
    pub fn reset_to(&self, stage: &str, _cache: &Cache) -> Result<()> {
        let dir = &self.target_dir;
        let mut found = false;
        for s in &self.stages {
            if s.name() == stage {
                found = true;
            }
            if found {
                let out_path = s.out_path(dir);
                let key_path = out_path.with_extension("cache_key");
                // `reset_to`'s contract is to INVALIDATE the named stage and every
                // stage after it. A swallowed removal failure (the old `let _ =`)
                // would report `Ok` while leaving a VALID cached artifact + sidecar,
                // so the next `build()` serves the stale artifact. Propagate every
                // error except "already absent" (idempotent for a not-yet-built stage).
                remove_if_present(&out_path)?;
                remove_if_present(&key_path)?;
            }
        }
        if !found {
            return Err(crate::error::Error::Artifact(format!(
                "Stage not found: {}",
                stage
            )));
        }
        Ok(())
    }
}

/// A pipeline stage that resolves abstract versions into exact cryptographic hashes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvePinsStage {
    /// Path to the pins.json file.
    pub pins_file: PathBuf,
}

#[async_trait]
impl Stage for ResolvePinsStage {
    fn name(&self) -> &str {
        "resolve_pins"
    }

    fn cache_key(&self, _inputs: &StageInputs) -> CacheKey {
        // Bump when this stage's resolution logic changes so stale outputs are not served.
        const STAGE_VERSION: u32 = 1;
        // Unambiguous field separator so distinct (pins, agent-hash) splits cannot
        // concatenate to the same byte stream (non-injective-hash defense).
        const SEP: &[u8] = b"\x1f";
        let content = std::fs::read_to_string(&self.pins_file).unwrap_or_default();
        let mut hasher = blake3::Hasher::new();
        hasher.update(&STAGE_VERSION.to_le_bytes());
        hasher.update(SEP);
        hasher.update(content.as_bytes());
        hasher.update(SEP);
        // Fold the FULL guest-agent source closure (bin wrapper + src/agent/** +
        // Cargo.lock), not just the thin wrapper, so a change to `src/agent/mod.rs`
        // invalidates the resolved pins. Otherwise a cache hit here skips re-hashing
        // the agent and a stale `guest_agent_src_hash` propagates downstream — the
        // stale-agent-baked-into-rootfs bug (H-CACHE-1).
        let agent_hash = guest_agent_closure_hash(&guest_agent_crate_root()).unwrap_or_default();
        hasher.update(agent_hash.as_bytes());
        CacheKey(format!("resolve-pins-{}", hasher.finalize().to_hex()))
    }

    fn out_path(&self, target_dir: &Path) -> PathBuf {
        target_dir.join("resolved_pins.json")
    }

    async fn run(&self, _inputs: &StageInputs, out: &Path) -> Result<StageOutputs> {
        let content = tokio::fs::read_to_string(&self.pins_file)
            .await
            .map_err(crate::error::Error::Io)?;
        tokio::fs::write(out, &content)
            .await
            .map_err(crate::error::Error::Io)?;

        let mut pins_map = parse_pins_json(&content)?;

        // Resolve the guest-agent source hash over the FULL source closure (the bin
        // wrapper PLUS every `src/agent/**/*.rs` it links PLUS `Cargo.lock`), anchored
        // at the crate root, and FAIL HARD if any of it is missing. Hashing only the
        // thin wrapper left a `src/agent/mod.rs` change invisible to every downstream
        // cache key, baking a stale agent into the rootfs (H-CACHE-1). A silent
        // `"unknown"` fallback would do the same without invalidating any key.
        let agent_hash = guest_agent_closure_hash(&guest_agent_crate_root())?;
        pins_map.insert("guest_agent_src_hash".to_string(), agent_hash);

        let mut outputs = StageOutputs::default();
        outputs
            .artifacts
            .insert("resolved_pins".to_string(), out.to_path_buf());
        outputs.pins = pins_map;
        Ok(outputs)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Guards the consolidated artifacts-dir default: a buggy resolver that drops the
    // default (or points it at `/tmp/...`) goes red here. Exercises the PURE inner fn so
    // there is no `std::env` mutation and therefore no cross-test env-var race.
    #[test]
    fn test_resolve_artifacts_dir_default_and_override() {
        let default = resolve_artifacts_dir(None);
        assert!(
            default.ends_with("target/vmcell-artifacts"),
            "default artifacts dir must be target/vmcell-artifacts, got {default:?}"
        );
        let overridden = resolve_artifacts_dir(Some("x/y".into()));
        assert_eq!(overridden, PathBuf::from("x/y"));
    }

    // Guards ARTIFACT-PIPELINE-5: a buggy impl that never emits
    // `debian_snapshot_timestamp` (so the mmdebstrap source can't run) goes red here.
    #[test]
    fn test_parse_pins_emits_debian_snapshot_timestamp() {
        let top = r#"{ "debian_snapshot_timestamp": "20240101T000000Z" }"#;
        let map = parse_pins_json(top).expect("valid pins JSON");
        assert_eq!(
            map.get("debian_snapshot_timestamp").map(String::as_str),
            Some("20240101T000000Z")
        );

        // Also accepted when nested under `rootfs`.
        let nested = r#"{ "rootfs": { "image": "docker.io/library/debian",
            "digest": "sha256:abc", "debian_snapshot_timestamp": "20240202T000000Z" } }"#;
        let map = parse_pins_json(nested).expect("valid pins JSON");
        assert_eq!(
            map.get("debian_snapshot_timestamp").map(String::as_str),
            Some("20240202T000000Z")
        );
        assert_eq!(
            map.get("rootfs_digest").map(String::as_str),
            Some("sha256:abc")
        );
    }

    // Guards the multi-kernel dimension: each `kernels.<label>` must flatten to
    // `kernel_<label>_source_url` / `_source_sha256` so a labelled KernelStage can
    // build it. A buggy impl that ignores `kernels` returns None for these keys.
    #[test]
    fn test_parse_pins_flattens_kernel_registry() {
        let json = r#"{
            "kernel": { "source_url": "u-default", "source_sha256": "s-default" },
            "kernels": {
                "6.6.143":  { "source_url": "u-66",  "source_sha256": "s-66"  },
                "6.12.94":  { "source_url": "u-612", "source_sha256": "s-612" }
            }
        }"#;
        let map = parse_pins_json(json).expect("valid pins JSON");
        assert_eq!(
            map.get("kernel_6.6.143_source_url").map(String::as_str),
            Some("u-66")
        );
        assert_eq!(
            map.get("kernel_6.6.143_source_sha256").map(String::as_str),
            Some("s-66")
        );
        assert_eq!(
            map.get("kernel_6.12.94_source_url").map(String::as_str),
            Some("u-612")
        );
        assert_eq!(
            map.get("kernel_6.12.94_source_sha256").map(String::as_str),
            Some("s-612")
        );
        // The default `kernel` pins stay intact alongside the registry.
        assert_eq!(
            map.get("kernel_source_url").map(String::as_str),
            Some("u-default")
        );
    }

    // Guards DESIGN-DIVERGENCE-3: a buggy impl that swallows a missing guest-agent source
    // into an `"unknown"` pin (instead of failing hard) would return Ok here.
    #[test]
    fn test_guest_agent_src_hash_fails_hard_on_missing() {
        let missing = Path::new("/nonexistent/imp/does-not-exist/vmcell-guest-agent.rs");
        let res = guest_agent_src_hash(missing);
        assert!(
            matches!(res, Err(crate::error::Error::Artifact(_))),
            "missing guest-agent source must be a hard error, got {res:?}"
        );
    }

    // Guards DESIGN-DIVERGENCE-3 (the hash actually tracks content): different source
    // bytes must yield a different hash, and the same bytes a stable one.
    #[test]
    fn test_guest_agent_src_hash_tracks_content() {
        let dir = tempfile::tempdir().expect("tempdir");
        let p = dir.path().join("agent.rs");
        std::fs::write(&p, b"fn main() {}").expect("write");
        let h1 = guest_agent_src_hash(&p).expect("hash");
        let h1b = guest_agent_src_hash(&p).expect("hash");
        assert_eq!(h1, h1b, "hash must be deterministic for identical content");

        std::fs::write(&p, b"fn main() { /* changed */ }").expect("write");
        let h2 = guest_agent_src_hash(&p).expect("hash");
        assert_ne!(h1, h2, "changed source content must change the hash");
    }

    // Guards M-PIPE-3: malformed pins JSON must fail loud here, not degrade to an
    // empty pin map that later surfaces as a misleading "Missing X pin". The buggy
    // `if let Ok(json)` swallow returned an empty map (Ok) → this `Err` match goes red.
    #[test]
    fn test_parse_pins_rejects_malformed_json() {
        let res = parse_pins_json("{ this is : not json ]");
        assert!(
            matches!(res, Err(crate::error::Error::Artifact(_))),
            "malformed pins JSON must be a hard error, got {res:?}"
        );
    }

    // Guards H-CACHE-1: the guest-agent identity must cover the FULL source closure
    // (bin wrapper + every src/agent/**/*.rs + Cargo.lock), not just the thin wrapper.
    // The buggy wrapper-only hash leaves a change to `src/agent/mod.rs` invisible, so
    // the rootfs cache key does NOT change and a stale agent is re-baked into the
    // rootfs. We mutate a NON-wrapper agent file and assert both the closure hash and
    // the downstream rootfs cache key change — both stay equal on the buggy version.
    #[cfg(feature = "pipeline")]
    #[test]
    fn test_guest_agent_closure_hash_tracks_agent_module_change() {
        use crate::artifact::rootfs::{RootfsBuildSource, RootfsStage};

        // A fixture "crate root" mirroring the real layout: the thin bin wrapper PLUS
        // the real logic under src/agent/**. Editing the real tree is avoided on purpose.
        let root = tempfile::tempdir().expect("tempdir");
        let bin_dir = root.path().join("src/bin");
        let agent_dir = root.path().join("src/agent");
        std::fs::create_dir_all(&bin_dir).expect("mkdir bin");
        std::fs::create_dir_all(&agent_dir).expect("mkdir agent");
        std::fs::write(bin_dir.join("vmcell-guest-agent.rs"), b"fn main() {}").expect("write bin");
        std::fs::write(agent_dir.join("mod.rs"), b"pub fn reaper() {}").expect("write mod");
        std::fs::write(agent_dir.join("protocol.rs"), b"pub struct Msg;").expect("write proto");
        std::fs::write(root.path().join("Cargo.lock"), b"# lock v1").expect("write lock");

        let h1 = guest_agent_closure_hash(root.path()).expect("closure hash 1");

        let rootfs = RootfsStage {
            source: RootfsBuildSource::Oci,
            cid_alloc: std::sync::Arc::new(crate::vmm::CidAllocator::new()),
        };
        let mut inputs1 = StageInputs::default();
        inputs1
            .pins
            .insert("guest_agent_src_hash".into(), h1.clone());
        let rootfs_key1 = rootfs.cache_key(&inputs1);

        // Mutate the agent IMPLEMENTATION (not the bin wrapper). The wrapper is
        // byte-identical, so the buggy wrapper-only hash would be UNCHANGED here.
        std::fs::write(agent_dir.join("mod.rs"), b"pub fn reaper() { /* fixed */ }")
            .expect("rewrite mod");
        let h2 = guest_agent_closure_hash(root.path()).expect("closure hash 2");
        assert_ne!(
            h1, h2,
            "a change to src/agent/mod.rs must change the guest-agent source closure hash"
        );

        let mut inputs2 = StageInputs::default();
        inputs2.pins.insert("guest_agent_src_hash".into(), h2);
        let rootfs_key2 = rootfs.cache_key(&inputs2);
        assert_ne!(
            rootfs_key1, rootfs_key2,
            "rootfs cache key must change when an agent implementation file changes"
        );
    }

    // Guards H-CACHE-1's hard-stop half: a missing bin wrapper (or src/agent tree)
    // must be a hard error, never a silent partial/empty closure hash.
    #[test]
    fn test_guest_agent_closure_hash_fails_hard_on_missing_bin() {
        let empty = tempfile::tempdir().expect("tempdir");
        let res = guest_agent_closure_hash(empty.path());
        assert!(
            matches!(res, Err(crate::error::Error::Artifact(_))),
            "missing guest-agent bin wrapper must be a hard error, got {res:?}"
        );
    }

    // Guards §11.2 caching rules 3-4 for vmcell-guest-tools: the helper links
    // reqwest/rustls, so a dependency bump changes Cargo.lock but NOT the `.rs`
    // source. The closure hash must fold Cargo.lock so the bump invalidates the
    // key. The buggy source-only hash (the old `if let Ok(content)` over just the
    // .rs) stays EQUAL across the lock change below and so re-bakes a stale helper.
    #[cfg(feature = "pipeline")]
    #[test]
    fn test_guest_tools_closure_hash_tracks_cargo_lock() {
        let root = tempfile::tempdir().expect("tempdir");
        let bin_dir = root.path().join("src/bin");
        std::fs::create_dir_all(&bin_dir).expect("mkdir bin");
        std::fs::write(bin_dir.join("vmcell-guest-tools.rs"), b"fn main() {}").expect("write bin");
        std::fs::write(root.path().join("Cargo.lock"), b"# lock v1").expect("write lock");

        let h1 = guest_tools_closure_hash(root.path()).expect("closure hash 1");

        // Bump a dependency: Cargo.lock changes, the helper `.rs` source does not.
        std::fs::write(root.path().join("Cargo.lock"), b"# lock v2 (dep bump)")
            .expect("rewrite lock");
        let h2 = guest_tools_closure_hash(root.path()).expect("closure hash 2");
        assert_ne!(
            h1, h2,
            "a Cargo.lock change (dependency bump) must change the guest-tools closure hash"
        );

        // Sanity: identical inputs hash identically (deterministic).
        std::fs::write(root.path().join("Cargo.lock"), b"# lock v1").expect("restore lock");
        let h1b = guest_tools_closure_hash(root.path()).expect("closure hash 1b");
        assert_eq!(h1, h1b, "identical closure inputs must hash identically");
    }

    // Guards the hard-stop half: a missing guest-tools bin source must be a hard
    // error, never a silent partial/empty closure hash that hits a stale cache.
    #[cfg(feature = "pipeline")]
    #[test]
    fn test_guest_tools_closure_hash_fails_hard_on_missing_bin() {
        let empty = tempfile::tempdir().expect("tempdir");
        let res = guest_tools_closure_hash(empty.path());
        assert!(
            matches!(res, Err(crate::error::Error::Artifact(_))),
            "missing guest-tools bin source must be a hard error, got {res:?}"
        );
    }
}
