//! VM artifact building and pipeline management.
//!
//! This module coordinates the building of artifacts required to boot and run
//! virtual machines, such as the kernel, root filesystem, and snapshots.

use crate::error::Result;
#[cfg(feature = "pipeline")]
/// Guest agent building stage.
pub mod guest_agent;
#[cfg(feature = "pipeline")]
/// Kernel building stage.
pub mod kernel;
#[cfg(feature = "pipeline")]
/// Root filesystem building stage.
pub mod rootfs;
#[cfg(feature = "pipeline")]
/// Snapshot building stage.
pub mod snapshot;
/// Tar to EROFS conversion utility.
#[cfg(feature = "am-fs-erofs")]
pub mod tar2erofs;

use std::path::{Path, PathBuf};

/// Inputs for an artifact building stage.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct StageInputs {
    /// Artifacts generated by previous stages.
    pub artifacts: std::collections::HashMap<String, PathBuf>,
}

/// Outputs from an artifact building stage.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct StageOutputs {
    /// Artifacts generated by this stage.
    pub artifacts: std::collections::HashMap<String, PathBuf>,
}

/// A cache key that uniquely identifies the inputs to a stage.
#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CacheKey(pub String);

use async_trait::async_trait;

#[async_trait]
/// A building block of the artifact pipeline.
pub trait Stage: Send + Sync {
    /// The name of this stage.
    fn name(&self) -> &str;
    /// Computes a cache key based on the stage configuration and inputs.
    fn cache_key(&self, inputs: &StageInputs) -> CacheKey;
    /// Returns the target path for the artifact.
    fn out_path(&self, target_dir: &Path) -> PathBuf;
    /// Executes the stage, building the output artifact at the given path.
    ///
    /// # Errors
    /// Returns an error if the build fails.
    async fn run(&self, inputs: &StageInputs, out: &Path) -> Result<StageOutputs>;
}

/// Cache for previously built artifacts.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Cache {}
/// Artifacts resulting from a pipeline build.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Artifacts {
    /// A mapping from artifact name to its location on disk.
    pub paths: std::collections::HashMap<String, PathBuf>,
}

/// A pipeline of stages to build all necessary test VM artifacts.
pub struct Pipeline {
    /// The sequence of stages to run.
    pub stages: Vec<Box<dyn Stage>>,
    /// The target directory for built artifacts.
    pub target_dir: PathBuf,
}

impl std::fmt::Debug for Pipeline {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Pipeline {{ {} stages }}", self.stages.len())
    }
}

impl Pipeline {
    /// Builds all artifacts in the pipeline.
    ///
    /// # Errors
    /// Returns an error if any stage fails.
    pub async fn build(&self, _cache: &Cache) -> Result<Artifacts> {
        let dir = &self.target_dir;
        match tokio::fs::create_dir_all(dir).await {
            Ok(_) => {}
            Err(e) => return Err(crate::error::Error::Io(e)),
        }

        let mut inputs = StageInputs::default();

        for stage in &self.stages {
            let out_path = stage.out_path(dir);

            let key = stage.cache_key(&inputs);
            let key_path = out_path.with_extension("cache_key");

            let mut cached = false;
            if out_path.exists() && key_path.exists() {
                if let Ok(saved_key) = std::fs::read_to_string(&key_path) {
                    if saved_key == key.0 {
                        cached = true;
                    }
                }
            }

            if cached {
                tracing::info!("Skipping stage {} (cached)", stage.name());
                inputs.artifacts.insert(stage.name().to_string(), out_path);
            } else {
                tracing::info!("Running stage {}", stage.name());
                let outputs = stage.run(&inputs, &out_path).await?;
                if let Err(e) = std::fs::write(&key_path, &key.0) {
                    tracing::warn!(
                        "Failed to write cache key for stage {}: {}",
                        stage.name(),
                        e
                    );
                }
                for (k, v) in outputs.artifacts {
                    inputs.artifacts.insert(k, v);
                }
            }
        }

        Ok(Artifacts {
            paths: inputs.artifacts,
        })
    }

    /// Resets the pipeline to run a specific stage again.
    ///
    /// # Errors
    /// Returns an error if the reset fails.
    pub fn reset_to(&self, stage: &str, _cache: &Cache) -> Result<()> {
        let dir = &self.target_dir;
        let mut found = false;
        for s in &self.stages {
            if s.name() == stage {
                found = true;
            }
            if found {
                let out_path = s.out_path(dir);
                let key_path = out_path.with_extension("cache_key");
                if out_path.exists() {
                    let _ = std::fs::remove_file(&out_path);
                }
                if key_path.exists() {
                    let _ = std::fs::remove_file(&key_path);
                }
            }
        }
        if !found {
            return Err(crate::error::Error::Artifact(format!(
                "Stage not found: {}",
                stage
            )));
        }
        Ok(())
    }
}
