[licenses]
allow = ["MIT", "Apache-2.0", "Apache-2.0 WITH LLVM-exception",
         "BSD-3-Clause", "BSD-2-Clause", "ISC", "Zlib", "0BSD", "Unicode-3.0"]

[bans]
multiple-versions = "warn"
wildcards = "deny"

[advisories]
yanked = "deny"
ignore = [
    "RUSTSEC-2020-0036", # failure is unmaintained
    "RUSTSEC-2026-0057", # Pending upstream fix
    "RUSTSEC-2026-0052", # Pending upstream fix
    "RUSTSEC-2026-0059", # Pending upstream fix
    "RUSTSEC-2026-0051", # Pending upstream fix
    "RUSTSEC-2026-0060", # Pending upstream fix
    "RUSTSEC-2026-0064", # Pending upstream fix
    "RUSTSEC-2026-0050", # Pending upstream fix
    "RUSTSEC-2026-0054", # Pending upstream fix
    "RUSTSEC-2026-0055", # Pending upstream fix
    "RUSTSEC-2026-0062", # Pending upstream fix
    "RUSTSEC-2026-0053", # Pending upstream fix
    "RUSTSEC-2026-0063", # Pending upstream fix
    "RUSTSEC-2026-0061", # Pending upstream fix
    "RUSTSEC-2026-0056", # Pending upstream fix
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
