//! VM artifact building and pipeline management.
//!
//! This module coordinates the building of artifacts required to boot and run
//! virtual machines, such as the kernel, root filesystem, and snapshots.

#![forbid(unsafe_code)]

use crate::error::Result;
#[cfg(feature = "pipeline")]
/// Reproducible fetch-and-verify manifest for the vmcell-owned artifacts (v15 §11).
pub mod bundle;
#[cfg(feature = "pipeline")]
/// Guest agent building stage.
pub mod guest_agent;
#[cfg(feature = "pipeline")]
/// Guest test-helper (`vmcell-guest-tools`) building stage.
pub mod guest_tools;
#[cfg(feature = "pipeline")]
/// Kernel building stage.
pub mod kernel;
#[cfg(feature = "pipeline")]
/// Root filesystem building stage.
pub mod rootfs;
#[cfg(feature = "pipeline")]
/// Snapshot building stage.
pub mod snapshot;
/// Tar to EROFS conversion utility.
#[cfg(feature = "am-fs-erofs")]
pub mod tar2erofs;

use std::path::{Path, PathBuf};

/// The VM-artifacts directory: `$VMCELL_ARTIFACTS_DIR`, else
/// `<workspace-root>/target/vmcell-artifacts`. The single source of truth for where built
/// artifacts (kernel, rootfs, CA) live.
///
/// v15: the default is anchored on the **workspace root** (not a CWD-relative
/// `target/vmcell-artifacts`) so it resolves identically whether the caller is the `vmcell`
/// CLI (CWD = workspace root) or an integration-test binary that cargo/nextest run with the
/// CWD set to `crates/vmcell/` — the workspace split changed the latter, which otherwise made
/// the suites fail-loud with "vmlinux artifact missing".
#[must_use]
pub fn artifacts_dir() -> PathBuf {
    resolve_artifacts_dir(std::env::var_os("VMCELL_ARTIFACTS_DIR"), &workspace_root())
}

/// Pure resolver behind [`artifacts_dir`], factored out so the default can be unit-tested
/// without mutating (and racing on) the process environment. The default is anchored on the
/// provided `ws_root`.
fn resolve_artifacts_dir(var: Option<std::ffi::OsString>, ws_root: &Path) -> PathBuf {
    var.map(PathBuf::from)
        .unwrap_or_else(|| ws_root.join("target/vmcell-artifacts"))
}

/// The guest kernel image path: `$VMCELL_KERNEL`, else `<artifacts_dir>/vmlinux`.
#[must_use]
pub fn kernel_path() -> PathBuf {
    std::env::var_os("VMCELL_KERNEL")
        .map(PathBuf::from)
        .unwrap_or_else(|| artifacts_dir().join("vmlinux"))
}

/// The rootfs erofs path: `$VMCELL_ROOTFS`, else `<artifacts_dir>/rootfs.erofs`.
#[must_use]
pub fn rootfs_path() -> PathBuf {
    std::env::var_os("VMCELL_ROOTFS")
        .map(PathBuf::from)
        .unwrap_or_else(|| artifacts_dir().join("rootfs.erofs"))
}

/// The cloud-hypervisor binary path: `$VMCELL_CH_BIN`, else bare `cloud-hypervisor`
/// (resolved on `PATH`).
///
/// The single source of truth for the CH binary so every stage that boots a VM
/// (the snapshot stage and the mmdebstrap builder stage) reads the **same** env var.
/// Previously the snapshot stage read `CLOUD_HYPERVISOR_PATH` while the builder read
/// `VMCELL_CH_BIN`, so overriding one left the other on the default — the kind of
/// per-call-site drift §11.1 consolidation and the `VMCELL_*` namespacing of §10.7-C
/// exist to prevent.
#[cfg(feature = "pipeline")]
pub(crate) fn ch_binary_path() -> String {
    std::env::var("VMCELL_CH_BIN").unwrap_or_else(|_| "cloud-hypervisor".to_string())
}

/// Inputs for an artifact building stage.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
#[non_exhaustive]
pub struct StageInputs {
    /// Artifacts generated by previous stages.
    pub artifacts: std::collections::HashMap<String, PathBuf>,
    /// Resolved string values (e.g. from pins.json) to pass down.
    pub pins: std::collections::HashMap<String, String>,
}

/// Outputs from an artifact building stage.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
#[non_exhaustive]
pub struct StageOutputs {
    /// Artifacts generated by this stage.
    pub artifacts: std::collections::HashMap<String, PathBuf>,
    /// Resolved string values (e.g. from pins.json) to pass down.
    pub pins: std::collections::HashMap<String, String>,
}

/// A cache key that uniquely identifies the inputs to a stage.
#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub struct CacheKey(pub String);

impl CacheKey {
    /// Wraps a precomputed cache-key string.
    ///
    /// Out-of-crate [`Stage`] implementations must use this constructor: the type
    /// is `#[non_exhaustive]`, so the tuple cannot be built directly from another
    /// crate.
    #[must_use]
    pub fn new(key: String) -> Self {
        Self(key)
    }
}

use async_trait::async_trait;

#[async_trait]
/// A building block of the artifact pipeline.
pub trait Stage: Send + Sync {
    /// The name of this stage.
    fn name(&self) -> &str;
    /// Computes a cache key based on the stage configuration and inputs.
    fn cache_key(&self, inputs: &StageInputs) -> CacheKey;
    /// Returns the target path for the artifact.
    fn out_path(&self, target_dir: &Path) -> PathBuf;
    /// Executes the stage, building the output artifact at the given path.
    ///
    /// # Errors
    /// Returns an error if the build fails.
    async fn run(&self, inputs: &StageInputs, out: &Path) -> Result<StageOutputs>;
}

/// Cache for previously built artifacts.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Cache {}
/// Artifacts resulting from a pipeline build.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub struct Artifacts {
    /// A mapping from artifact name to its location on disk.
    pub paths: std::collections::HashMap<String, PathBuf>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct CacheMetadata {
    key: String,
    hash: String,
    pins: std::collections::HashMap<String, String>,
    #[serde(default)]
    artifacts: std::collections::HashMap<String, PathBuf>,
}

pub(crate) fn hash_file(path: &Path) -> Result<String> {
    use std::io::Read;
    let mut file = std::fs::File::open(path).map_err(crate::error::Error::Io)?;
    let mut hasher = blake3::Hasher::new();
    let mut buf = [0; 65536];
    loop {
        let n = file.read(&mut buf).map_err(crate::error::Error::Io)?;
        if n == 0 {
            break;
        }
        hasher.update(buf.get(..n).expect("valid slice"));
    }
    Ok(hasher.finalize().to_hex().to_string())
}

/// Content hash of a stage output, whether it is a single **file** or a **directory**.
///
/// A file hashes to exactly [`hash_file`] (so existing file sidecars stay valid). A
/// directory (e.g. the `SnapshotStage` output — ART-1) hashes over a deterministic,
/// sorted recursive walk — relative name + type + (files) mode + content, (symlinks)
/// target — so the whole tree is content-addressed and a byte-corrupted file inside it is
/// rejected on the cache-hit path exactly like a tampered single-file artifact. Using
/// `hash_file` on a directory `File::open`s it and reads → `EISDIR`, which silently
/// defeated caching *and* tamper-verification for every directory output.
///
/// # Errors
/// Returns [`crate::error::Error::Io`] if `path` (or any entry under it) cannot be read.
pub(crate) fn hash_output(path: &Path) -> Result<String> {
    let meta = std::fs::symlink_metadata(path).map_err(crate::error::Error::Io)?;
    if meta.is_dir() {
        let mut hasher = blake3::Hasher::new();
        hasher.update(b"vmcell-dir-v1\0");
        hash_dir_into(&mut hasher, path)?;
        Ok(hasher.finalize().to_hex().to_string())
    } else {
        hash_file(path)
    }
}

/// Folds a directory's contents into `hasher` over a deterministic sorted walk, so the
/// hash is stable regardless of the filesystem's `read_dir` ordering.
fn hash_dir_into(hasher: &mut blake3::Hasher, dir: &Path) -> Result<()> {
    use std::os::unix::ffi::OsStrExt;
    use std::os::unix::fs::PermissionsExt;
    let mut entries: Vec<std::fs::DirEntry> = std::fs::read_dir(dir)
        .map_err(crate::error::Error::Io)?
        .collect::<std::result::Result<Vec<_>, _>>()
        .map_err(crate::error::Error::Io)?;
    entries.sort_by_key(std::fs::DirEntry::file_name);
    for entry in entries {
        let name = entry.file_name();
        let file_type = entry.file_type().map_err(crate::error::Error::Io)?;
        let path = entry.path();
        // `OsStr::as_bytes` preserves non-UTF-8 names (L-ART-5): `to_string_lossy` collapses
        // distinct non-UTF-8 names to U+FFFD, so two different filenames could hash the same.
        hasher.update(name.as_bytes());
        hasher.update(b"\0");
        if file_type.is_dir() {
            hasher.update(b"d");
            // Fold the directory's own mode (L-ART-5) so a chmod on a directory inside the
            // tree changes the hash (previously only file modes were folded).
            let meta = entry.metadata().map_err(crate::error::Error::Io)?;
            hasher.update(&meta.permissions().mode().to_le_bytes());
            hash_dir_into(hasher, &path)?;
        } else if file_type.is_symlink() {
            hasher.update(b"l");
            let target = std::fs::read_link(&path).map_err(crate::error::Error::Io)?;
            // Preserve a non-UTF-8 symlink target too (L-ART-5).
            hasher.update(target.as_os_str().as_bytes());
        } else {
            hasher.update(b"f");
            let meta = entry.metadata().map_err(crate::error::Error::Io)?;
            hasher.update(&meta.permissions().mode().to_le_bytes());
            hasher.update(hash_file(&path)?.as_bytes());
        }
        hasher.update(b"\x1e");
    }
    Ok(())
}

/// Removes `path` if it exists, returning `Ok(())` when it is already absent and
/// propagating every other I/O error (e.g. permission denied).
///
/// Handles both a **file** (`remove_file`) and a **directory** (`remove_dir_all`) — the
/// snapshot stage's output is a directory (ART-1/ART-2), so a `remove_file`-only path
/// returned `EISDIR` and made `reset_to(<stage at/before snapshot>)` fail once the
/// snapshot dir existed, defeating invalidation. A symlink is removed as a link, never
/// followed into its target's tree.
///
/// Used by [`Pipeline::reset_to`] so a failed invalidation is loud, never a silent `Ok`
/// that leaves a stale cached artifact behind.
///
/// # Errors
/// Returns [`crate::error::Error::Io`] if the path exists but cannot be removed.
fn remove_if_present(path: &Path) -> Result<()> {
    match std::fs::symlink_metadata(path) {
        Ok(meta) if meta.is_dir() => std::fs::remove_dir_all(path).map_err(crate::error::Error::Io),
        Ok(_) => std::fs::remove_file(path).map_err(crate::error::Error::Io),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(crate::error::Error::Io(e)),
    }
}

/// Folds the upstream `artifacts` into `hasher` in a deterministic, key-sorted order,
/// hashing each artifact's on-disk **content** (the identity that travels) rather than its
/// absolute path under `target_dir`. An artifact not yet materialized on disk folds a
/// stable `<unmaterialized>` marker (never its absolute path).
///
/// Iterating the raw `HashMap` would feed blake3 in a process-random order (spurious cache
/// misses) and would key on `target_dir`-relative path strings (a rebuilt upstream at the
/// same path would not invalidate the key). Sorting + content-hashing fixes both.
#[cfg(feature = "pipeline")]
pub(crate) fn hash_artifacts_sorted(
    hasher: &mut blake3::Hasher,
    artifacts: &std::collections::HashMap<String, PathBuf>,
) {
    let sorted: std::collections::BTreeMap<&String, &PathBuf> = artifacts.iter().collect();
    for (k, v) in sorted {
        hasher.update(k.as_bytes());
        // `hash_output` (not `hash_file`) so a DIRECTORY artifact (e.g. the snapshot-stage
        // output) is content-hashed over its recursive walk (M-ART-6). `hash_file` on a
        // directory `File::open`s it and reads -> `EISDIR`, indistinguishable from the
        // genuine-miss `NotFound` arm below — so a content change to a file INSIDE a
        // directory artifact would not invalidate a downstream key.
        match hash_output(v) {
            Ok(content_hash) => {
                hasher.update(b"c:");
                hasher.update(content_hash.as_bytes());
            }
            Err(_) => {
                // The artifact is not materialized on disk yet. Fold a STABLE marker —
                // never the absolute `PathBuf` under `target/`, a non-traveling identity
                // (B4/ART-8): keying on the absolute path makes the cache key vary by where
                // `target/` lives and lets a rebuilt upstream at the same path go unnoticed.
                // The resulting cache miss re-runs the stage, whose `run()` then fails loud
                // on the genuinely-missing input.
                hasher.update(b"u:<unmaterialized>");
            }
        }
    }
}

/// Parses the resolved-pins JSON document into a flat map of pin keys.
///
/// Extracted as a pure helper so the pin extraction (including the
/// `debian_snapshot_timestamp` the mmdebstrap source depends on) is unit-testable.
///
/// # Errors
/// Returns [`crate::error::Error::Artifact`] if `content` is not valid JSON. A
/// tampered/garbled `pins.json` must fail loud here — the old code swallowed the
/// parse error and degraded to an empty map, which only surfaced later as a
/// misleading "Missing X pin" far from the real cause (A8 — verify what you ingest).
fn parse_pins_json(content: &str) -> Result<std::collections::HashMap<String, String>> {
    let json = serde_json::from_str::<serde_json::Value>(content)
        .map_err(|e| crate::error::Error::Artifact(format!("malformed pins JSON: {e}")))?;
    let mut pins_map = std::collections::HashMap::new();
    if let Some(k) = json.get("kernel") {
        if let Some(sha) = k.get("source_sha256").and_then(|v| v.as_str()) {
            pins_map.insert("kernel_source_sha256".to_string(), sha.to_string());
        }
        if let Some(url) = k.get("source_url").and_then(|v| v.as_str()) {
            pins_map.insert("kernel_source_url".to_string(), url.to_string());
        }
        if let Some(cfg) = k.get("microvm_config").and_then(|v| v.as_str()) {
            pins_map.insert("kernel_microvm_config".to_string(), cfg.to_string());
        }
    }
    // Flatten the multi-kernel registry: each `kernels.<label>` → keyed pins
    // (`kernel_<label>_source_url` / `_source_sha256`), so a labelled `KernelStage`
    // can build `vmlinux-<label>` — the kernel-version benchmark dimension. They
    // share the default `kernel`'s `microvm_config`.
    if let Some(kernels) = json.get("kernels").and_then(|v| v.as_object()) {
        for (label, spec) in kernels {
            if let Some(url) = spec.get("source_url").and_then(|v| v.as_str()) {
                pins_map.insert(format!("kernel_{label}_source_url"), url.to_string());
            }
            if let Some(sha) = spec.get("source_sha256").and_then(|v| v.as_str()) {
                pins_map.insert(format!("kernel_{label}_source_sha256"), sha.to_string());
            }
        }
    }
    // Flatten the kernel config-fragment registry (§8.3): each `kernel_fragments.<NAME>` →
    // a `kernel_fragments_<NAME>` pin holding that fragment's KConfig text, which a
    // `KernelStage` with `fragments = [NAME, ...]` layers onto the base config (content-
    // addressed, so editing a fragment's text invalidates the cache).
    if let Some(fragments) = json.get("kernel_fragments").and_then(|v| v.as_object()) {
        for (name, cfg) in fragments {
            if let Some(text) = cfg.as_str() {
                pins_map.insert(format!("kernel_fragments_{name}"), text.to_string());
            }
        }
    }
    if let Some(r) = json.get("rootfs") {
        if let Some(img) = r.get("image").and_then(|v| v.as_str()) {
            pins_map.insert("rootfs_image".to_string(), img.to_string());
        }
        if let Some(dig) = r.get("digest").and_then(|v| v.as_str()) {
            pins_map.insert("rootfs_digest".to_string(), dig.to_string());
        }
    }
    // Emit the CH/virtiofsd build identity for the snapshot pool (§16 / M-ART-7): a snapshot
    // is only valid for the exact CH build that produced it, so the snapshot stage folds the
    // `cloud_hypervisor` pin into its cache key. Emitted only when present in pins.json.
    for key in ["cloud_hypervisor", "virtiofsd"] {
        if let Some(v) = json.get(key).and_then(|v| v.as_str()) {
            pins_map.insert(key.to_string(), v.to_string());
        }
    }
    // Emit the Debian snapshot.debian.org timestamp pin if present (top-level or under
    // `rootfs`) so the mmdebstrap source has its required source timestamp.
    let ts = json
        .get("debian_snapshot_timestamp")
        .and_then(|v| v.as_str())
        .or_else(|| {
            json.get("rootfs")
                .and_then(|r| r.get("debian_snapshot_timestamp"))
                .and_then(|v| v.as_str())
        });
    if let Some(ts) = ts {
        pins_map.insert("debian_snapshot_timestamp".to_string(), ts.to_string());
    }
    Ok(pins_map)
}

/// Computes the blake3 hash of the guest-agent source file at `path`.
///
/// # Errors
/// Returns [`crate::error::Error::Artifact`] if the source cannot be read. This is a hard
/// stop on purpose: a missing guest-agent source must not silently degrade to an `"unknown"`
/// pin (which would leave a stale agent baked into every downstream rootfs).
fn guest_agent_src_hash(path: &Path) -> Result<String> {
    let src = std::fs::read_to_string(path).map_err(|e| {
        crate::error::Error::Artifact(format!(
            "failed to read guest-agent source at {}: {}",
            path.display(),
            e
        ))
    })?;
    let mut hasher = blake3::Hasher::new();
    hasher.update(src.as_bytes());
    Ok(hasher.finalize().to_hex().to_string())
}

/// The workspace root — the anchor for the artifacts dir and the guest-agent /
/// guest-tools source closures (v15 §10.1). Ascends from `CARGO_MANIFEST_DIR` (the
/// `vmcell` crate dir under the workspace) — or, when that is unset, the **absolute**
/// process CWD — to the directory that owns the member crates, so the resolved paths
/// are stable regardless of where the binary runs.
///
/// The CWD fallback uses [`std::env::current_dir`] (absolute) rather than a bare `.`
/// **on purpose**: cargo/nextest run a workspace member's test binaries with the CWD
/// set to that member's dir (`crates/vmcell/`), and a relative `.` has no usable
/// ancestors to ascend, so the artifacts under the workspace `target/` would not be
/// found. The marker is `crates/vmcell-protocol/Cargo.toml`, a stable landmark.
pub(crate) fn workspace_root() -> PathBuf {
    let start = std::env::var_os("CARGO_MANIFEST_DIR")
        .map(PathBuf::from)
        .or_else(|| std::env::current_dir().ok())
        .unwrap_or_else(|| PathBuf::from("."));
    for dir in start.ancestors() {
        if dir.join("crates/vmcell-protocol/Cargo.toml").is_file() {
            return dir.to_path_buf();
        }
    }
    // No marker found (e.g. a bare binary run outside the workspace) — fall back to the
    // starting dir so callers still get a usable, absolute-when-possible anchor.
    start
}

/// Recursively collects every `*.rs` file under `dir` into `out`.
///
/// # Errors
/// Returns [`crate::error::Error::Artifact`] if `dir` (or a subdirectory) cannot
/// be read — the agent logic must exist, so a missing source tree is a hard stop
/// rather than a silent partial hash.
fn collect_rs_files(dir: &Path, out: &mut Vec<PathBuf>) -> Result<()> {
    let entries = std::fs::read_dir(dir).map_err(|e| {
        crate::error::Error::Artifact(format!(
            "failed to read guest-agent source dir {}: {}",
            dir.display(),
            e
        ))
    })?;
    for entry in entries {
        let entry = entry.map_err(crate::error::Error::Io)?;
        let file_type = entry.file_type().map_err(crate::error::Error::Io)?;
        let path = entry.path();
        if file_type.is_dir() {
            collect_rs_files(&path, out)?;
        } else if path.extension().and_then(|e| e.to_str()) == Some("rs") {
            out.push(path);
        }
    }
    Ok(())
}

/// Hashes the **full source closure** the `vmcell-guest-agent` binary compiles
/// from: every `*.rs` under `crates/vmcell-guest-agent/src/` (the binary entry
/// point plus the reaper library it links — `ReaperCoordinator`,
/// `exit_code_from_termination`) **plus** every `*.rs` under
/// `crates/vmcell-protocol/src/` (the shared wire `protocol` it links) **plus**
/// `Cargo.lock` (the pinned dependency versions). All paths are taken relative to
/// the workspace root and folded in a deterministic, sorted order.
///
/// Hashing only the binary wrapper (the old behavior) left every downstream cache
/// key blind to a change in the agent's real logic: editing the reaper or the
/// post-restore vsock re-bind left the hash unchanged, so all three cache keys
/// (resolve-pins, guest-agent, rootfs) hit and a **stale agent binary was re-baked
/// into `rootfs.erofs`**. The closure must travel as one identity (H-CACHE-1).
///
/// # Errors
/// Returns [`crate::error::Error::Artifact`] if the binary entry point is missing,
/// either source tree cannot be read, or any closure file cannot be read — a hard
/// stop, never a silent partial or `"unknown"` hash.
pub(crate) fn guest_agent_closure_hash(ws_root: &Path) -> Result<String> {
    // The agent binary entry point is mandatory; its absence is the same hard stop.
    let main_rs = ws_root.join("crates/vmcell-guest-agent/src/main.rs");
    if !main_rs.is_file() {
        return Err(crate::error::Error::Artifact(format!(
            "guest-agent binary source missing at {}",
            main_rs.display()
        )));
    }
    let mut files: Vec<PathBuf> = Vec::new();
    // Every Rust source file the agent binary links: its own crate (main + reaper
    // lib) plus the shared wire-protocol crate.
    collect_rs_files(&ws_root.join("crates/vmcell-guest-agent/src"), &mut files)?;
    collect_rs_files(&ws_root.join("crates/vmcell-protocol/src"), &mut files)?;
    // Cargo.lock pins the dependency versions the agent compiles against; fold it
    // if present (a workspace may build the lock only on demand).
    let lock = ws_root.join("Cargo.lock");
    if lock.is_file() {
        files.push(lock);
    }
    // Deterministic order regardless of `read_dir` order.
    files.sort();

    let mut hasher = blake3::Hasher::new();
    for f in &files {
        // Fold the workspace-relative path (so a rename/move invalidates) with an
        // unambiguous delimiter, then the file's content hash.
        let rel = f.strip_prefix(ws_root).unwrap_or(f.as_path());
        hasher.update(rel.to_string_lossy().as_bytes());
        hasher.update(b"\0");
        hasher.update(guest_agent_src_hash(f)?.as_bytes());
        hasher.update(b"\0");
    }
    Ok(hasher.finalize().to_hex().to_string())
}

/// Hashes the **source closure** the `vmcell-guest-tools` helper binary compiles
/// from: every `*.rs` under `crates/vmcell-guest-tools/src/` **plus** `Cargo.lock`
/// (the pinned dependency versions). Files are taken relative to the workspace
/// root and folded in a deterministic, sorted order with a stable hasher (blake3)
/// — mirroring [`guest_agent_closure_hash`].
///
/// Folding `Cargo.lock` is the whole point: `vmcell-guest-tools` links
/// reqwest/rustls, so a dependency bump changes the **built** helper while the
/// `.rs` source is byte-identical. Hashing only the source (the old behavior) left
/// the cache key unchanged on a bump, so the stage hit cache and a stale
/// `ip`/`curl`/`kvm-ok` helper was re-baked into the rootfs (§11.2 caching rules
/// 3-4). The closure must travel as one identity.
///
/// # Errors
/// Returns [`crate::error::Error::Artifact`] if the binary source is missing, or
/// any closure file cannot be read — a hard stop, never a silent partial hash (the
/// old `if let Ok(content)` swallow that quietly produced a content-blind key).
#[cfg(feature = "pipeline")]
pub(crate) fn guest_tools_closure_hash(ws_root: &Path) -> Result<String> {
    // The bin source is mandatory; its absence is a hard stop.
    let main_rs = ws_root.join("crates/vmcell-guest-tools/src/main.rs");
    if !main_rs.is_file() {
        return Err(crate::error::Error::Artifact(format!(
            "guest-tools binary source missing at {}",
            main_rs.display()
        )));
    }
    let mut files: Vec<PathBuf> = Vec::new();
    collect_rs_files(&ws_root.join("crates/vmcell-guest-tools/src"), &mut files)?;
    // Cargo.lock pins the dependency versions the helper compiles against; fold it
    // if present (a workspace may build the lock only on demand).
    let lock = ws_root.join("Cargo.lock");
    if lock.is_file() {
        files.push(lock);
    }
    // Deterministic order regardless of filesystem enumeration.
    files.sort();

    let mut hasher = blake3::Hasher::new();
    for f in &files {
        // Fold the workspace-relative path (so a rename/move invalidates) with an
        // unambiguous delimiter, then the file's content hash. `guest_agent_src_hash`
        // is a generic fail-hard file-content hash reused here.
        let rel = f.strip_prefix(ws_root).unwrap_or(f.as_path());
        hasher.update(rel.to_string_lossy().as_bytes());
        hasher.update(b"\0");
        hasher.update(guest_agent_src_hash(f)?.as_bytes());
        hasher.update(b"\0");
    }
    Ok(hasher.finalize().to_hex().to_string())
}

/// A pipeline of stages to build all necessary test VM artifacts.
///
/// The fields are private: a stage list is only assembled through
/// [`Pipeline::new`] + [`Pipeline::add_stage`], so an external caller cannot
/// mutate `stages` to drop or reorder Stage 0 (`ResolvePinsStage`) and bypass the
/// "Stage 0 resolves pins" invariant.
pub struct Pipeline {
    /// The sequence of stages to run.
    stages: Vec<Box<dyn Stage>>,
    /// The target directory for built artifacts.
    target_dir: PathBuf,
}

impl std::fmt::Debug for Pipeline {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Pipeline {{ {} stages }}", self.stages.len())
    }
}

impl Pipeline {
    /// Creates an empty pipeline that writes artifacts under `target_dir`.
    #[must_use]
    pub fn new(target_dir: PathBuf) -> Self {
        Self {
            stages: Vec::new(),
            target_dir,
        }
    }

    /// Appends a stage to the pipeline, returning `self` for chaining.
    #[must_use]
    pub fn add_stage(mut self, stage: Box<dyn Stage>) -> Self {
        self.stages.push(stage);
        self
    }

    /// Builds all artifacts in the pipeline.
    ///
    /// # Errors
    /// Returns an error if any stage fails.
    pub async fn build(&self, _cache: &Cache) -> Result<Artifacts> {
        let dir = &self.target_dir;
        match tokio::fs::create_dir_all(dir).await {
            Ok(_) => {}
            Err(e) => return Err(crate::error::Error::Io(e)),
        }

        let mut inputs = StageInputs::default();

        for stage in &self.stages {
            let out_path = stage.out_path(dir);

            let key = stage.cache_key(&inputs);
            let key_path = out_path.with_extension("cache_key");

            let mut cached = false;
            let mut cached_pins = std::collections::HashMap::new();
            let mut cached_artifacts = std::collections::HashMap::new();

            if out_path.exists() && key_path.exists() {
                // The sidecar EXISTS (checked above), so a read failure is a real I/O error
                // (permission denied / EISDIR), never a genuine miss. Fail loud (L-ART-4)
                // rather than silently treat a locked/tampered cache as a rebuild.
                let metadata_str =
                    std::fs::read_to_string(&key_path).map_err(crate::error::Error::Io)?;
                if let Ok(metadata) = serde_json::from_str::<CacheMetadata>(&metadata_str) {
                    if metadata.key == key.0 {
                        // `hash_output` (not `hash_file`) so a DIRECTORY output (the snapshot
                        // stage — ART-1) is content-hashed over a sorted walk and
                        // tamper-verified. The output EXISTS (checked), so a hash failure is a
                        // real I/O error, not a miss — surface it, don't silently rebuild
                        // (L-ART-4).
                        let actual_hash = hash_output(&out_path)?;
                        if actual_hash == metadata.hash {
                            cached = true;
                            cached_pins = metadata.pins;
                            cached_artifacts = metadata.artifacts;
                        } else {
                            return Err(crate::error::Error::Artifact(format!(
                                "Tampered artifact for stage {}: payload hash mismatch",
                                stage.name()
                            )));
                        }
                    }
                } else {
                    // Fallback for old cache key format: just a string
                    if metadata_str == key.0 {
                        // Can't verify hash or recover pins. Miss cache to force rebuild and get proper format.
                        tracing::warn!(
                            "Cache invalid for stage {}: old cache format",
                            stage.name()
                        );
                    }
                }
            }

            if cached {
                tracing::info!("Skipping stage {} (cached)", stage.name());
                if cached_artifacts.is_empty() {
                    inputs
                        .artifacts
                        .insert(stage.name().to_string(), out_path.clone());
                } else {
                    for (k, v) in cached_artifacts {
                        inputs.artifacts.insert(k, v);
                    }
                }
                for (k, v) in cached_pins {
                    inputs.pins.insert(k, v);
                }
            } else {
                tracing::info!("Running stage {}", stage.name());
                let outputs = stage.run(&inputs, &out_path).await?;

                // Hash payload and write metadata. `hash_output` handles a directory
                // output (the snapshot stage — ART-1): `hash_file` `File::open`ed the dir
                // and `EISDIR`-ed into the `warn!` arm, so no `.cache_key` sidecar was ever
                // written and the most expensive stage was never cached or tamper-verified.
                if out_path.exists() {
                    match hash_output(&out_path) {
                        Ok(hash) => {
                            let metadata = CacheMetadata {
                                key: key.0.clone(),
                                hash,
                                pins: outputs.pins.clone(),
                                artifacts: outputs.artifacts.clone(),
                            };
                            if let Ok(json) = serde_json::to_string(&metadata) {
                                if let Err(e) = std::fs::write(&key_path, json) {
                                    tracing::warn!(
                                        "Failed to write cache key for stage {}: {}",
                                        stage.name(),
                                        e
                                    );
                                }
                            }
                        }
                        Err(e) => {
                            tracing::warn!(
                                "Failed to hash output for stage {}: {}",
                                stage.name(),
                                e
                            );
                        }
                    }
                }

                for (k, v) in outputs.artifacts {
                    inputs.artifacts.insert(k, v);
                }
                for (k, v) in outputs.pins {
                    inputs.pins.insert(k, v);
                }
            }
        }

        Ok(Artifacts {
            paths: inputs.artifacts,
        })
    }

    /// Resets the pipeline to run a specific stage again.
    ///
    /// # Errors
    /// Returns an error if the reset fails.
    pub fn reset_to(&self, stage: &str, _cache: &Cache) -> Result<()> {
        let dir = &self.target_dir;
        let mut found = false;
        for s in &self.stages {
            if s.name() == stage {
                found = true;
            }
            if found {
                let out_path = s.out_path(dir);
                let key_path = out_path.with_extension("cache_key");
                // `reset_to`'s contract is to INVALIDATE the named stage and every
                // stage after it. A swallowed removal failure (the old `let _ =`)
                // would report `Ok` while leaving a VALID cached artifact + sidecar,
                // so the next `build()` serves the stale artifact. Propagate every
                // error except "already absent" (idempotent for a not-yet-built stage).
                remove_if_present(&out_path)?;
                remove_if_present(&key_path)?;
            }
        }
        if !found {
            return Err(crate::error::Error::Artifact(format!(
                "Stage not found: {}",
                stage
            )));
        }
        Ok(())
    }
}

/// Pipeline Stage 0: publishes the committed `pins.json` lock into the pipeline.
///
/// Despite the "resolve" name, this stage does **not** perform live version→digest
/// resolution (that is the deferred `ARTIFACT-PIPELINE-5`); it reads the *already
/// committed* `pins.json` (the lock), copies it to `resolved_pins.json`, flattens its
/// entries into the propagated `pins` map, and folds in the guest-agent source-closure
/// hash so downstream stages consume pins purely from memory (ART-6).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvePinsStage {
    /// Path to the pins.json file.
    pub pins_file: PathBuf,
}

#[async_trait]
impl Stage for ResolvePinsStage {
    fn name(&self) -> &str {
        "resolve_pins"
    }

    fn cache_key(&self, _inputs: &StageInputs) -> CacheKey {
        // Bump when this stage's resolution logic changes so stale outputs are not served.
        const STAGE_VERSION: u32 = 1;
        // Unambiguous field separator so distinct (pins, agent-hash) splits cannot
        // concatenate to the same byte stream (non-injective-hash defense).
        const SEP: &[u8] = b"\x1f";
        let mut hasher = blake3::Hasher::new();
        hasher.update(&STAGE_VERSION.to_le_bytes());
        hasher.update(SEP);
        // Fold the pins content — or, on a read failure, a DISTINCT error marker rather
        // than `unwrap_or_default()`'s empty string (ART-11). Collapsing every read error
        // (missing file, permission denied, …) to `""` made all of them share one key, and
        // aliased with a genuinely-empty pins file. Folding the error keeps the key
        // distinct; the resulting cache miss drives `run()`, which fails hard with the real
        // cause. Mirrors `GuestToolsStage::cache_key`.
        match std::fs::read_to_string(&self.pins_file) {
            Ok(content) => hasher.update(content.as_bytes()),
            Err(e) => hasher.update(format!("resolve-pins-read-error:{e}").as_bytes()),
        };
        hasher.update(SEP);
        // Fold the FULL guest-agent source closure (bin wrapper + src/agent/** +
        // Cargo.lock), not just the thin wrapper, so a change to `src/agent/mod.rs`
        // invalidates the resolved pins. Otherwise a cache hit here skips re-hashing
        // the agent and a stale `guest_agent_src_hash` propagates downstream — the
        // stale-agent-baked-into-rootfs bug (H-CACHE-1). A closure-hash failure folds a
        // distinct error marker (not `unwrap_or_default()`'s `""`) for the same ART-11
        // reason.
        match guest_agent_closure_hash(&workspace_root()) {
            Ok(h) => hasher.update(h.as_bytes()),
            Err(e) => hasher.update(format!("resolve-pins-agent-closure-error:{e}").as_bytes()),
        };
        CacheKey(format!("resolve-pins-{}", hasher.finalize().to_hex()))
    }

    fn out_path(&self, target_dir: &Path) -> PathBuf {
        target_dir.join("resolved_pins.json")
    }

    async fn run(&self, _inputs: &StageInputs, out: &Path) -> Result<StageOutputs> {
        let content = tokio::fs::read_to_string(&self.pins_file)
            .await
            .map_err(crate::error::Error::Io)?;
        tokio::fs::write(out, &content)
            .await
            .map_err(crate::error::Error::Io)?;

        let mut pins_map = parse_pins_json(&content)?;

        // Resolve the guest-agent source hash over the FULL source closure (the bin
        // wrapper PLUS every `src/agent/**/*.rs` it links PLUS `Cargo.lock`), anchored
        // at the crate root, and FAIL HARD if any of it is missing. Hashing only the
        // thin wrapper left a `src/agent/mod.rs` change invisible to every downstream
        // cache key, baking a stale agent into the rootfs (H-CACHE-1). A silent
        // `"unknown"` fallback would do the same without invalidating any key.
        let agent_hash = guest_agent_closure_hash(&workspace_root())?;
        pins_map.insert("guest_agent_src_hash".to_string(), agent_hash);

        let mut outputs = StageOutputs::default();
        outputs
            .artifacts
            .insert("resolved_pins".to_string(), out.to_path_buf());
        outputs.pins = pins_map;
        Ok(outputs)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Guards the consolidated artifacts-dir default: a buggy resolver that drops the
    // default (or points it at `/tmp/...`) goes red here. Exercises the PURE inner fn so
    // there is no `std::env` mutation and therefore no cross-test env-var race.
    #[test]
    fn test_resolve_artifacts_dir_default_and_override() {
        // The default is anchored on the provided workspace root (so it resolves the same
        // regardless of the process CWD — the v15 workspace-split fix).
        let default = resolve_artifacts_dir(None, Path::new("/ws"));
        assert_eq!(default, PathBuf::from("/ws/target/vmcell-artifacts"));
        let overridden = resolve_artifacts_dir(Some("x/y".into()), Path::new("/ws"));
        assert_eq!(overridden, PathBuf::from("x/y"));
    }

    // Guards ARTIFACT-PIPELINE-5: a buggy impl that never emits
    // `debian_snapshot_timestamp` (so the mmdebstrap source can't run) goes red here.
    #[test]
    fn test_parse_pins_emits_debian_snapshot_timestamp() {
        let top = r#"{ "debian_snapshot_timestamp": "20240101T000000Z" }"#;
        let map = parse_pins_json(top).expect("valid pins JSON");
        assert_eq!(
            map.get("debian_snapshot_timestamp").map(String::as_str),
            Some("20240101T000000Z")
        );

        // Also accepted when nested under `rootfs`.
        let nested = r#"{ "rootfs": { "image": "docker.io/library/debian",
            "digest": "sha256:abc", "debian_snapshot_timestamp": "20240202T000000Z" } }"#;
        let map = parse_pins_json(nested).expect("valid pins JSON");
        assert_eq!(
            map.get("debian_snapshot_timestamp").map(String::as_str),
            Some("20240202T000000Z")
        );
        assert_eq!(
            map.get("rootfs_digest").map(String::as_str),
            Some("sha256:abc")
        );
    }

    // Guards the multi-kernel dimension: each `kernels.<label>` must flatten to
    // `kernel_<label>_source_url` / `_source_sha256` so a labelled KernelStage can
    // build it. A buggy impl that ignores `kernels` returns None for these keys.
    #[test]
    fn test_parse_pins_flattens_kernel_registry() {
        let json = r#"{
            "kernel": { "source_url": "u-default", "source_sha256": "s-default" },
            "kernels": {
                "6.6.143":  { "source_url": "u-66",  "source_sha256": "s-66"  },
                "6.12.94":  { "source_url": "u-612", "source_sha256": "s-612" }
            }
        }"#;
        let map = parse_pins_json(json).expect("valid pins JSON");
        assert_eq!(
            map.get("kernel_6.6.143_source_url").map(String::as_str),
            Some("u-66")
        );
        assert_eq!(
            map.get("kernel_6.6.143_source_sha256").map(String::as_str),
            Some("s-66")
        );
        assert_eq!(
            map.get("kernel_6.12.94_source_url").map(String::as_str),
            Some("u-612")
        );
        assert_eq!(
            map.get("kernel_6.12.94_source_sha256").map(String::as_str),
            Some("s-612")
        );
        // The default `kernel` pins stay intact alongside the registry.
        assert_eq!(
            map.get("kernel_source_url").map(String::as_str),
            Some("u-default")
        );
    }

    // §8.3: each `kernel_fragments.<NAME>` must flatten to a `kernel_fragments_<NAME>` pin
    // carrying that fragment's KConfig text, so a `KernelStage` with `fragments=[NAME]` can
    // resolve it. A buggy impl that ignores `kernel_fragments` returns None for these keys
    // and the kernel build would then fail loud on the missing fragment.
    #[test]
    fn test_parse_pins_flattens_kernel_fragments() {
        let json = r#"{
            "kernel_fragments": {
                "KASAN":   "CONFIG_KASAN=y\n",
                "LOCKDEP": "CONFIG_LOCKDEP=y\n"
            }
        }"#;
        let map = parse_pins_json(json).expect("valid pins JSON");
        assert_eq!(
            map.get("kernel_fragments_KASAN").map(String::as_str),
            Some("CONFIG_KASAN=y\n")
        );
        assert_eq!(
            map.get("kernel_fragments_LOCKDEP").map(String::as_str),
            Some("CONFIG_LOCKDEP=y\n")
        );
    }

    // Guards DESIGN-DIVERGENCE-3: a buggy impl that swallows a missing guest-agent source
    // into an `"unknown"` pin (instead of failing hard) would return Ok here.
    #[test]
    fn test_guest_agent_src_hash_fails_hard_on_missing() {
        let missing = Path::new("/nonexistent/imp/does-not-exist/vmcell-guest-agent.rs");
        let res = guest_agent_src_hash(missing);
        assert!(
            matches!(res, Err(crate::error::Error::Artifact(_))),
            "missing guest-agent source must be a hard error, got {res:?}"
        );
    }

    // Guards DESIGN-DIVERGENCE-3 (the hash actually tracks content): different source
    // bytes must yield a different hash, and the same bytes a stable one.
    #[test]
    fn test_guest_agent_src_hash_tracks_content() {
        let dir = tempfile::tempdir().expect("tempdir");
        let p = dir.path().join("agent.rs");
        std::fs::write(&p, b"fn main() {}").expect("write");
        let h1 = guest_agent_src_hash(&p).expect("hash");
        let h1b = guest_agent_src_hash(&p).expect("hash");
        assert_eq!(h1, h1b, "hash must be deterministic for identical content");

        std::fs::write(&p, b"fn main() { /* changed */ }").expect("write");
        let h2 = guest_agent_src_hash(&p).expect("hash");
        assert_ne!(h1, h2, "changed source content must change the hash");
    }

    // Guards M-PIPE-3: malformed pins JSON must fail loud here, not degrade to an
    // empty pin map that later surfaces as a misleading "Missing X pin". The buggy
    // `if let Ok(json)` swallow returned an empty map (Ok) → this `Err` match goes red.
    #[test]
    fn test_parse_pins_rejects_malformed_json() {
        let res = parse_pins_json("{ this is : not json ]");
        assert!(
            matches!(res, Err(crate::error::Error::Artifact(_))),
            "malformed pins JSON must be a hard error, got {res:?}"
        );
    }

    // Guards H-CACHE-1: the guest-agent identity must cover the FULL source closure
    // (bin wrapper + every src/agent/**/*.rs + Cargo.lock), not just the thin wrapper.
    // The buggy wrapper-only hash leaves a change to `src/agent/mod.rs` invisible, so
    // the rootfs cache key does NOT change and a stale agent is re-baked into the
    // rootfs. We mutate a NON-wrapper agent file and assert both the closure hash and
    // the downstream rootfs cache key change — both stay equal on the buggy version.
    #[cfg(feature = "pipeline")]
    #[test]
    fn test_guest_agent_closure_hash_tracks_agent_module_change() {
        use crate::artifact::rootfs::{RootfsBuildSource, RootfsStage};

        // A fixture "workspace root" mirroring the real v15 layout: the guest-agent
        // member (binary entry point + reaper lib) PLUS the shared protocol crate it
        // links. Editing the real tree is avoided on purpose.
        let root = tempfile::tempdir().expect("tempdir");
        let agent_src = root.path().join("crates/vmcell-guest-agent/src");
        let proto_src = root.path().join("crates/vmcell-protocol/src");
        std::fs::create_dir_all(&agent_src).expect("mkdir agent src");
        std::fs::create_dir_all(&proto_src).expect("mkdir protocol src");
        // The workspace-root marker the closure-hash anchor ascends to.
        std::fs::write(
            root.path().join("crates/vmcell-protocol/Cargo.toml"),
            b"[package]\nname=\"vmcell-protocol\"\n",
        )
        .expect("write protocol manifest");
        std::fs::write(agent_src.join("main.rs"), b"fn main() {}").expect("write bin");
        std::fs::write(agent_src.join("lib.rs"), b"pub fn reaper() {}").expect("write lib");
        std::fs::write(proto_src.join("lib.rs"), b"pub struct Msg;").expect("write proto");
        std::fs::write(root.path().join("Cargo.lock"), b"# lock v1").expect("write lock");

        let h1 = guest_agent_closure_hash(root.path()).expect("closure hash 1");

        let rootfs = RootfsStage {
            source: RootfsBuildSource::Oci,
            cid_alloc: std::sync::Arc::new(crate::vmm::CidAllocator::new()),
            image_override: None,
            agent_musl: None,
        };
        let mut inputs1 = StageInputs::default();
        inputs1
            .pins
            .insert("guest_agent_src_hash".into(), h1.clone());
        let rootfs_key1 = rootfs.cache_key(&inputs1);

        // Mutate the agent IMPLEMENTATION (not the binary entry point). main.rs is
        // byte-identical, so the buggy entry-point-only hash would be UNCHANGED here.
        std::fs::write(agent_src.join("lib.rs"), b"pub fn reaper() { /* fixed */ }")
            .expect("rewrite lib");
        let h2 = guest_agent_closure_hash(root.path()).expect("closure hash 2");
        assert_ne!(
            h1, h2,
            "a change to the guest-agent reaper lib must change the source closure hash"
        );

        let mut inputs2 = StageInputs::default();
        inputs2.pins.insert("guest_agent_src_hash".into(), h2);
        let rootfs_key2 = rootfs.cache_key(&inputs2);
        assert_ne!(
            rootfs_key1, rootfs_key2,
            "rootfs cache key must change when an agent implementation file changes"
        );
    }

    // Guards H-CACHE-1's hard-stop half: a missing bin wrapper (or src/agent tree)
    // must be a hard error, never a silent partial/empty closure hash.
    #[test]
    fn test_guest_agent_closure_hash_fails_hard_on_missing_bin() {
        let empty = tempfile::tempdir().expect("tempdir");
        let res = guest_agent_closure_hash(empty.path());
        assert!(
            matches!(res, Err(crate::error::Error::Artifact(_))),
            "missing guest-agent bin wrapper must be a hard error, got {res:?}"
        );
    }

    // Guards §11.2 caching rules 3-4 for vmcell-guest-tools: the helper links
    // reqwest/rustls, so a dependency bump changes Cargo.lock but NOT the `.rs`
    // source. The closure hash must fold Cargo.lock so the bump invalidates the
    // key. The buggy source-only hash (the old `if let Ok(content)` over just the
    // .rs) stays EQUAL across the lock change below and so re-bakes a stale helper.
    #[cfg(feature = "pipeline")]
    #[test]
    fn test_guest_tools_closure_hash_tracks_cargo_lock() {
        let root = tempfile::tempdir().expect("tempdir");
        let tools_src = root.path().join("crates/vmcell-guest-tools/src");
        std::fs::create_dir_all(&tools_src).expect("mkdir tools src");
        std::fs::write(tools_src.join("main.rs"), b"fn main() {}").expect("write bin");
        std::fs::write(root.path().join("Cargo.lock"), b"# lock v1").expect("write lock");

        let h1 = guest_tools_closure_hash(root.path()).expect("closure hash 1");

        // Bump a dependency: Cargo.lock changes, the helper `.rs` source does not.
        std::fs::write(root.path().join("Cargo.lock"), b"# lock v2 (dep bump)")
            .expect("rewrite lock");
        let h2 = guest_tools_closure_hash(root.path()).expect("closure hash 2");
        assert_ne!(
            h1, h2,
            "a Cargo.lock change (dependency bump) must change the guest-tools closure hash"
        );

        // Sanity: identical inputs hash identically (deterministic).
        std::fs::write(root.path().join("Cargo.lock"), b"# lock v1").expect("restore lock");
        let h1b = guest_tools_closure_hash(root.path()).expect("closure hash 1b");
        assert_eq!(h1, h1b, "identical closure inputs must hash identically");
    }

    // Guards the hard-stop half: a missing guest-tools bin source must be a hard
    // error, never a silent partial/empty closure hash that hits a stale cache.
    #[cfg(feature = "pipeline")]
    #[test]
    fn test_guest_tools_closure_hash_fails_hard_on_missing_bin() {
        let empty = tempfile::tempdir().expect("tempdir");
        let res = guest_tools_closure_hash(empty.path());
        assert!(
            matches!(res, Err(crate::error::Error::Artifact(_))),
            "missing guest-tools bin source must be a hard error, got {res:?}"
        );
    }

    // ART-8: an unmaterialized upstream artifact must fold a STABLE marker, never its
    // absolute `PathBuf` — otherwise the key varies by where `target/` lives and a rebuilt
    // upstream at the same path is invisible. Two DIFFERENT absent absolute paths under the
    // same artifact key must produce the SAME fold. The buggy `p:` + `to_string_lossy`
    // path-fold makes these diverge → red here.
    #[cfg(feature = "pipeline")]
    #[test]
    fn test_hash_artifacts_unmaterialized_is_path_independent() {
        let mut m1 = std::collections::HashMap::new();
        m1.insert("k".to_string(), PathBuf::from("/nonexistent/aaa/x"));
        let mut m2 = std::collections::HashMap::new();
        m2.insert("k".to_string(), PathBuf::from("/nonexistent/bbb/deeper/y"));
        let mut h1 = blake3::Hasher::new();
        hash_artifacts_sorted(&mut h1, &m1);
        let mut h2 = blake3::Hasher::new();
        hash_artifacts_sorted(&mut h2, &m2);
        assert_eq!(
            h1.finalize(),
            h2.finalize(),
            "an absent artifact must fold a stable marker, not its absolute path (ART-8)"
        );
    }

    // ART-1: a directory output hashes deterministically over its content, and a
    // byte-corrupted file INSIDE it changes the hash — so the cache-hit tamper check can
    // reject it. `hash_file` would `File::open` the dir and `EISDIR` here instead.
    #[test]
    fn test_hash_output_directory_deterministic_and_tamper_sensitive() {
        let dir = tempfile::tempdir().expect("tempdir");
        let snap = dir.path().join("snapshot");
        std::fs::create_dir_all(snap.join("mem")).expect("mkdir");
        std::fs::write(snap.join("state.json"), b"state-v1").expect("write");
        std::fs::write(snap.join("mem/pages.bin"), b"pages-v1").expect("write");

        let h1 = hash_output(&snap).expect("hash dir");
        let h1b = hash_output(&snap).expect("hash dir again");
        assert_eq!(h1, h1b, "directory content hash must be deterministic");

        // Corrupt one file inside the directory: the hash must change.
        std::fs::write(snap.join("mem/pages.bin"), b"pages-TAMPERED").expect("write");
        let h2 = hash_output(&snap).expect("hash dir after tamper");
        assert_ne!(
            h1, h2,
            "a corrupted file inside the directory must change the content hash"
        );
    }

    // ART-2: `remove_if_present` purges a NON-EMPTY directory (via `remove_dir_all`),
    // removes a file, and treats an already-absent path as success — never `EISDIR` on a
    // directory (which defeated `reset_to` for the snapshot stage).
    #[test]
    fn test_remove_if_present_file_dir_and_absent() {
        let tmp = tempfile::tempdir().expect("tempdir");

        // A regular file is removed.
        let f = tmp.path().join("file");
        std::fs::write(&f, b"x").expect("write");
        remove_if_present(&f).expect("remove file");
        assert!(!f.exists());

        // A non-empty directory (the snapshot-dir case) is purged, not EISDIR-errored.
        let d = tmp.path().join("dir");
        std::fs::create_dir_all(d.join("sub")).expect("mkdir");
        std::fs::write(d.join("sub/inner"), b"y").expect("write");
        remove_if_present(&d).expect("remove dir must succeed, not EISDIR");
        assert!(!d.exists());

        // An already-absent path is idempotent success.
        remove_if_present(&tmp.path().join("never")).expect("absent is Ok");
    }

    // M-ART-7: `parse_pins_json` must emit the CH/virtiofsd build identity so the snapshot
    // stage can fold it. A buggy impl that ignores these keys returns None -> red.
    #[test]
    fn test_parse_pins_emits_ch_virtiofsd_identity() {
        let json = r#"{ "cloud_hypervisor": "v40.0", "virtiofsd": "v1.11.0" }"#;
        let map = parse_pins_json(json).expect("valid pins JSON");
        assert_eq!(
            map.get("cloud_hypervisor").map(String::as_str),
            Some("v40.0")
        );
        assert_eq!(map.get("virtiofsd").map(String::as_str), Some("v1.11.0"));
    }

    // M-ART-6: a DIRECTORY artifact must be content-hashed by `hash_artifacts_sorted`, so a
    // content change to a file inside it changes the fold. The buggy `hash_file`-on-a-dir
    // EISDIRs and folds the `unmaterialized` marker regardless -> the two folds stay equal.
    #[cfg(feature = "pipeline")]
    #[test]
    fn test_hash_artifacts_sorted_directory() {
        let dir = tempfile::tempdir().expect("tempdir");
        let snap = dir.path().join("snapshot");
        std::fs::create_dir_all(&snap).expect("mkdir");
        std::fs::write(snap.join("state.bin"), b"state-v1").expect("write");
        let mut m = std::collections::HashMap::new();
        m.insert("snapshot".to_string(), snap.clone());

        let mut h1 = blake3::Hasher::new();
        hash_artifacts_sorted(&mut h1, &m);
        let d1 = h1.finalize();

        std::fs::write(snap.join("state.bin"), b"state-v2-tampered").expect("write");
        let mut h2 = blake3::Hasher::new();
        hash_artifacts_sorted(&mut h2, &m);
        let d2 = h2.finalize();

        assert_ne!(
            d1, d2,
            "a directory artifact's content change must change the fold (M-ART-6)"
        );
    }

    // L-ART-5: `hash_dir_into` must preserve non-UTF-8 names/targets (not `to_string_lossy`)
    // and fold directory modes. (1) two distinct non-UTF-8 filenames that collapse to the
    // same U+FFFD must hash differently; (2) a chmod on a directory inside the tree must
    // change the hash. Both go red on the lossy / no-dir-mode buggy version.
    #[test]
    fn test_hash_dir_preserves_non_utf8_names_and_dir_modes() {
        use std::os::unix::ffi::OsStrExt;
        use std::os::unix::fs::PermissionsExt;
        let dir = tempfile::tempdir().expect("tempdir");
        let root = dir.path().join("tree");
        std::fs::create_dir_all(&root).unwrap();

        let name_a = std::ffi::OsStr::from_bytes(b"\xff");
        let name_b = std::ffi::OsStr::from_bytes(b"\xfe");
        let pa = root.join(name_a);
        std::fs::write(&pa, b"x").unwrap();
        let h_a = hash_output(&root).expect("hash");
        std::fs::rename(&pa, root.join(name_b)).unwrap();
        let h_b = hash_output(&root).expect("hash");
        assert_ne!(
            h_a, h_b,
            "distinct non-UTF-8 names must not collapse to the same hash (L-ART-5)"
        );

        let sub = root.join("sub");
        std::fs::create_dir(&sub).unwrap();
        std::fs::set_permissions(&sub, std::fs::Permissions::from_mode(0o755)).unwrap();
        let h1 = hash_output(&root).expect("hash");
        std::fs::set_permissions(&sub, std::fs::Permissions::from_mode(0o700)).unwrap();
        let h2 = hash_output(&root).expect("hash");
        assert_ne!(
            h1, h2,
            "a directory-mode change inside the tree must change the hash (L-ART-5)"
        );
    }

    /// A trivial stage whose output is a fixed file, for the cache-bookkeeping tests.
    struct TrivialStage;
    #[async_trait::async_trait]
    impl Stage for TrivialStage {
        fn name(&self) -> &str {
            "trivial"
        }
        fn cache_key(&self, _: &StageInputs) -> CacheKey {
            CacheKey("trivial-k".into())
        }
        fn out_path(&self, t: &Path) -> PathBuf {
            t.join("trivial_out")
        }
        async fn run(&self, _: &StageInputs, out: &Path) -> Result<StageOutputs> {
            tokio::fs::write(out, b"out")
                .await
                .map_err(crate::error::Error::Io)?;
            Ok(StageOutputs::default())
        }
    }

    // L-ART-4: an existing-but-unreadable cache sidecar must fail the build LOUD, never fall
    // through to a silent rebuild. A directory at the sidecar path makes `read_to_string`
    // EISDIR regardless of uid; the buggy `if let Ok(metadata_str)` swallows it (build Ok),
    // so this `is_err()` assertion goes red on the old behavior.
    #[tokio::test]
    async fn test_build_fails_loud_on_unreadable_sidecar() {
        let dir = tempfile::tempdir().expect("tempdir");
        let target = dir.path().to_path_buf();
        let out = target.join("trivial_out");
        std::fs::write(&out, b"out").unwrap();
        std::fs::create_dir_all(out.with_extension("cache_key")).unwrap();
        let pipeline = Pipeline::new(target).add_stage(Box::new(TrivialStage));
        let res = pipeline.build(&Cache::default()).await;
        assert!(
            res.is_err(),
            "an existing-but-unreadable cache sidecar must fail the build loud (L-ART-4)"
        );
    }

    /// Stage A of the warm-hit restoration test: constant key, emits a pin + an artifact.
    #[cfg(feature = "pipeline")]
    struct WarmStageA;
    #[cfg(feature = "pipeline")]
    #[async_trait::async_trait]
    impl Stage for WarmStageA {
        fn name(&self) -> &str {
            "A"
        }
        fn cache_key(&self, _: &StageInputs) -> CacheKey {
            CacheKey("A-const".into())
        }
        fn out_path(&self, t: &Path) -> PathBuf {
            t.join("A_out")
        }
        async fn run(&self, _: &StageInputs, out: &Path) -> Result<StageOutputs> {
            tokio::fs::write(out, b"a-content")
                .await
                .map_err(crate::error::Error::Io)?;
            let mut o = StageOutputs::default();
            o.pins.insert("my_pin".into(), "value".into());
            o.artifacts.insert("my_artifact".into(), out.to_path_buf());
            Ok(o)
        }
    }

    /// Stage B: its key folds both the restored pin AND the restored artifact content, and
    /// its run() requires both — so deleting either restoration loop re-runs it.
    #[cfg(feature = "pipeline")]
    struct WarmStageB {
        runs: std::sync::Arc<std::sync::atomic::AtomicUsize>,
    }
    #[cfg(feature = "pipeline")]
    #[async_trait::async_trait]
    impl Stage for WarmStageB {
        fn name(&self) -> &str {
            "B"
        }
        fn cache_key(&self, inputs: &StageInputs) -> CacheKey {
            let mut h = blake3::Hasher::new();
            h.update(b"B");
            match inputs.pins.get("my_pin") {
                Some(v) => h.update(v.as_bytes()),
                None => h.update(b"<no-pin>"),
            };
            let filtered: std::collections::HashMap<String, PathBuf> = inputs
                .artifacts
                .iter()
                .filter(|(k, _)| k.as_str() == "my_artifact")
                .map(|(k, v)| (k.clone(), v.clone()))
                .collect();
            hash_artifacts_sorted(&mut h, &filtered);
            CacheKey(format!("B-{}", h.finalize().to_hex()))
        }
        fn out_path(&self, t: &Path) -> PathBuf {
            t.join("B_out")
        }
        async fn run(&self, inputs: &StageInputs, out: &Path) -> Result<StageOutputs> {
            self.runs.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
            inputs
                .pins
                .get("my_pin")
                .ok_or_else(|| crate::error::Error::Artifact("Missing pin my_pin".into()))?;
            inputs.artifacts.get("my_artifact").ok_or_else(|| {
                crate::error::Error::Artifact("Missing artifact my_artifact".into())
            })?;
            tokio::fs::write(out, b"b-content")
                .await
                .map_err(crate::error::Error::Io)?;
            Ok(StageOutputs::default())
        }
    }

    // M-ART-12: on a warm cache hit of stage A, its cached pins AND artifacts must be
    // restored into `inputs` so a downstream stage B still keys/consumes them. Deleting the
    // `cached_pins` loop (B fails "Missing pin"/re-runs) or the `cached_artifacts` loop (B
    // re-keys and re-runs) makes B run a second time -> the `== 1` assertion goes red.
    #[cfg(feature = "pipeline")]
    #[tokio::test]
    async fn test_warm_hit_restores_pins_and_artifacts_downstream() {
        let dir = tempfile::tempdir().expect("tempdir");
        let runs = std::sync::Arc::new(std::sync::atomic::AtomicUsize::new(0));
        let mk = || {
            Pipeline::new(dir.path().to_path_buf())
                .add_stage(Box::new(WarmStageA))
                .add_stage(Box::new(WarmStageB { runs: runs.clone() }))
        };
        // Cold build: A and B both run.
        mk().build(&Cache::default()).await.expect("cold build");
        assert_eq!(
            runs.load(std::sync::atomic::Ordering::SeqCst),
            1,
            "B runs once on the cold build"
        );
        // Warm build: A cache-hits and MUST restore my_pin + my_artifact so B stays cached.
        mk().build(&Cache::default()).await.expect("warm build");
        assert_eq!(
            runs.load(std::sync::atomic::Ordering::SeqCst),
            1,
            "B must stay cached on the warm build; a dropped restoration loop re-runs it (M-ART-12)"
        );
    }
}
